<?php
/**
 * Admission Number Service
 *
 * Single source of truth for the admission-number format. The configured
 * format lives in school_settings.admission_no_format (default
 * `KPS{seq}`) and supports three tokens:
 *
 *   {year}    -> 4-digit year
 *   {seq}     -> per-year sequence, unpadded
 *   {seq:NN}  -> per-year sequence, zero-padded to NN digits
 *
 * Sequence numbers are generated by the DB function fn_generate_admission_no,
 * which increments the per-year counter in number_sequences atomically so
 * concurrent enrollments never collide. This service adds the PHP-side
 * validation/format helpers used by StudentsAPI::create().
 *
 * @package App\API\Services
 * @since 2026-08-15
 */

namespace App\API\Services;

use PDO;

class AdmissionNumberService
{
    public const DEFAULT_FORMAT = 'KPS{seq}';

    /** @var PDO */
    private $db;

    public function __construct(PDO $db)
    {
        $this->db = $db;
    }

    /**
     * Read the configured admission-number format, falling back to the default.
     */
    public function getFormat(): string
    {
        $stmt = $this->db->prepare("SELECT setting_value FROM school_settings WHERE setting_key = 'admission_no_format' LIMIT 1");
        $stmt->execute();
        $format = $stmt->fetchColumn();

        return ($format === false || $format === null || $format === '') ? self::DEFAULT_FORMAT : (string) $format;
    }

    /**
     * Generate the next admission number for the given year using the DB
     * function (collision-safe, per-year sequence).
     */
    public function generate(int $year): string
    {
        $stmt = $this->db->prepare("SELECT fn_generate_admission_no(:year)");
        $stmt->execute(['year' => $year]);
        $number = $stmt->fetchColumn();

        return (string) $number;
    }

    /**
     * Normalize a number supplied while registering an existing learner.
     * Staff may enter 400 or KPS400; storage is always KPS400.
     */
    public function normalizeExisting(string $value): ?string
    {
        // Historical registers sometimes contain letters, spaces or labels.
        // Keep the numeric portion and apply the canonical school prefix.
        $digits = preg_replace('/\D+/', '', trim($value));
        if ($digits === '') {
            return null;
        }
        $digits = ltrim($digits, '0');
        return 'KPS' . ($digits === '' ? '0' : $digits);
    }

    public function isAvailable(string $admissionNo): bool
    {
        $stmt = $this->db->prepare('SELECT 1 FROM students WHERE admission_no = ? LIMIT 1');
        $stmt->execute([$admissionNo]);
        return $stmt->fetchColumn() === false;
    }

    /**
     * Continue the KPS sequence from the most recently inserted numbered
     * learner. Called inside the learner creation transaction.
     */
    public function generateNextExisting(): string
    {
        $stmt = $this->db->query(
            "SELECT admission_no FROM students
             WHERE admission_no REGEXP '^KPS[0-9]+$'
             ORDER BY id DESC LIMIT 1 FOR UPDATE"
        );
        $last = (string) ($stmt->fetchColumn() ?: '');
        $sequence = preg_match('/^KPS(\d+)$/', $last, $matches) ? (int) $matches[1] + 1 : 1;

        do {
            $candidate = 'KPS' . $sequence++;
        } while (!$this->isAvailable($candidate));

        return $candidate;
    }

    /**
     * Build a PCRE pattern from a format template so an existing admission
     * number can be validated against the configured format.
     */
    public function buildPattern(string $format): string
    {
        $pattern = '';

        $i = 0;
        $len = strlen($format);
        while ($i < $len) {
            if (substr($format, $i, 6) === '{year}') {
                $pattern .= '\d{4}';
                $i += 6;
                continue;
            }
            if (substr($format, $i, 5) === '{seq}') {
                $pattern .= '\d+';
                $i += 5;
                continue;
            }
            if (substr($format, $i, 5) === '{seq:') {
                $end = strpos($format, '}', $i);
                $width = $end !== false ? substr($format, $i + 5, $end - ($i + 5)) : '';
                if (ctype_digit($width) && (int) $width > 0) {
                    $pattern .= '\d{' . (int) $width . '}';
                    $i = $end + 1;
                } else {
                    $pattern .= '\d+';
                    $i += 5;
                }
                continue;
            }
            $pattern .= preg_quote($format[$i], '/');
            $i++;
        }

        return '/^' . $pattern . '$/';
    }

    /**
     * Check whether an admission number matches the configured format.
     */
    public function isValid(string $admissionNo, ?string $format = null): bool
    {
        $format = $format ?? $this->getFormat();
        return preg_match($this->buildPattern($format), $admissionNo) === 1;
    }
}
