<?php

declare(strict_types=1);

namespace App\API\Services;

use App\API\Includes\FileLogger;
use App\Config\Config;
use Throwable;

/**
 * Service-to-service bridge from the PHP edge to the Python AI platform.
 *
 * Architecture (the "Python is the AI engine" model):
 *   - PHP keeps ONLY authentication, RBAC, row scope, queues and the
 *     governed data tools; it relays the already-authorized operator
 *     envelope to Python and returns the structured answer verbatim.
 *   - Python (ai_platform/, Passenger WSGI app) owns all agent logic:
 *     provider calls, triage, tool loops, prompts, behaviour study and
 *     digest automations. Every data tool Python needs is executed back
 *     through POST /api/dashboard/agent-tool, which re-authorizes the
 *     recorded operator inside PHP - the model never touches school data.
 *   - The PHP-native AiAgentService remains as the offline/resilience
 *     path when the Python platform is not configured or is redeploying.
 *
 * Transport is curl (shared-hosting verified), bearer-authenticated with
 * the shared AI_PYTHON_SECRET, bounded timeouts, and never logs payloads.
 */
final class AiPythonBridge
{
    public const ENDPOINT_ASSIST = '/api/agents/assist';
    public const ENDPOINT_DIGEST = '/api/agents/digest';
    public const ENDPOINT_BRIEFING = '/api/agents/briefing';

    /** @var callable|null Injectable transport for hermetic tests: fn(string $url, string $method, array $headers, string $body, int $timeout): array{0:string|false,1:int,2:string} */
    private $transport;

    public function __construct(?callable $transport = null)
    {
        $this->transport = $transport;
    }

    public function available(): bool
    {
        return trim((string) Config::get('AI_PYTHON_URL', '')) !== '';
    }

    /**
     * Full governed agent run in the Python platform. Returns the same
     * answer contract as AiAgentService::assist so controllers and the
     * frontend never know which engine ran.
     *
     * @param array<string,mixed> $context
     * @return array<string,mixed>
     */
    public function assist(array $context, string $question): array
    {
        return $this->call(self::ENDPOINT_ASSIST, [
            'context' => [
                'user_id' => (int) ($context['user_id'] ?? 0),
                'permissions' => array_values(array_unique(array_map('strval', array_merge(
                    (array) ($context['effective_permissions'] ?? []),
                    (array) ($context['permissions'] ?? [])
                )))),
                'audience' => 'staff',
                'route' => mb_substr((string) ($context['route'] ?? ''), 0, 120),
                'module' => mb_substr((string) ($context['module'] ?? 'dashboard'), 0, 60),
                'request_id' => mb_substr((string) ($context['request_id'] ?? 'ai-python-bridge'), 0, 100),
            ],
            'question' => $question,
        ]);
    }

    /**
     * @param array<int,int|string> $permissions
     * @return array<string,mixed>
     */
    public function digest(int $userId, array $permissions, string $cadence = 'daily', string $requestId = 'ai-python-bridge', bool $broadcast = false): array
    {
        return $this->call(self::ENDPOINT_DIGEST, [
            'context' => [
                'user_id' => $userId,
                'permissions' => array_values(array_map('strval', $permissions)),
                'audience' => 'staff',
                'route' => '',
                'module' => 'dashboard',
                'request_id' => mb_substr($requestId, 0, 100),
            ],
            'cadence' => $cadence,
            'broadcast' => $broadcast,
        ]);
    }

    /**
     * Proactive workspace briefing generated by the Python engine: the
     * governed scan plus the LLM narrative (findings, root causes,
     * suggested actions). Same page-load caching contract as the insight
     * brief: fresh cache serves immediately, stale enqueues regeneration.
     */
    public function briefing(int $userId, array $permissions, string $route, string $requestId = 'ai-python-briefing'): array
    {
        return $this->call(self::ENDPOINT_BRIEFING, [
            'context' => [
                'user_id' => $userId,
                'permissions' => array_values(array_map('strval', $permissions)),
                'audience' => 'staff',
                'route' => mb_substr($route, 0, 120),
                'module' => 'dashboard',
                'request_id' => mb_substr($requestId, 0, 100),
            ],
            'route' => mb_substr($route, 0, 120),
        ]);
    }

    /**
     * Execute an ai.agent.run queue job through the Python platform and
     * cache the result under the shared insight key so page loads and the
     * PHP-native engine observe one consistent contract.
     *
     * @param array<string,mixed> $payload
     * @return array<string,mixed>
     */
    public function runJob(array $payload): array
    {
        $userId = (int) ($payload['user_id'] ?? 0);
        $hint = AiAgentService::permissionHint(
            array_values(array_map('strval', (array) ($payload['permissions'] ?? []))),
            200
        );
        $permissions = $hint['permissions'];
        $requestId = mb_substr((string) ($payload['request_id'] ?? 'ai-agent-run'), 0, 100);
        $mode = (string) ($payload['mode'] ?? 'digest');
        if ($mode === 'assist') {
            $result = $this->assist([
                'user_id' => $userId,
                'permissions' => $permissions,
                'effective_permissions' => $permissions,
                'request_id' => $requestId,
                'audience' => 'staff',
                'route' => (string) ($payload['route'] ?? ''),
                'module' => (string) ($payload['module'] ?? 'dashboard'),
            ], (string) ($payload['question'] ?? ''));
        } elseif ($mode === 'briefing') {
            $route = mb_substr((string) ($payload['route'] ?? ''), 0, 120);
            $result = $this->briefing($userId, $permissions, $route, $requestId);
            if ($userId > 0) {
                $this->cacheBriefingResult($userId, $route, $result);
            }
            return $result;
        } else {
            $result = $this->digest($userId, $permissions, (string) ($payload['cadence'] ?? 'daily'), $requestId, !empty($payload['broadcast']));
        }
        if ($userId > 0) {
            try {
                (new SharedCache())->set(AiAgentService::CACHE_PREFIX . $userId, $result, AiInsightOrchestrator::BRIEF_TTL);
            } catch (Throwable $e) {
                FileLogger::write('ai_generation', [
                    'type' => 'agent_cache_failed',
                    'mode' => $mode,
                    'error_class' => get_class($e),
                    'message' => mb_substr($e->getMessage(), 0, 160),
                ]);
            }
        }
        return $result;
    }

    /**
     * Publish the generated briefing for page-load serving. The write is
     * best-effort but journaled: a silent cache failure would otherwise make
     * every panel open regenerate.
     *
     * @param array<string,mixed> $briefing
     */
    private function cacheBriefingResult(int $userId, string $route, array $briefing): void
    {
        try {
            $written = (new SharedCache())->set(
                AiAgentService::briefingCacheKey($userId, $route),
                $briefing,
                AiAgentService::BRIEFING_TTL
            );
            FileLogger::write('ai_generation', [
                'type' => 'agent_briefing_cached',
                'operator_id' => $userId,
                'route' => $route,
                'engine' => (string) ($briefing['engine'] ?? ''),
                'written' => (bool) $written,
            ]);
        } catch (Throwable $e) {
            FileLogger::write('ai_generation', [
                'type' => 'agent_briefing_cache_failed',
                'operator_id' => $userId,
                'route' => $route,
                'error_class' => get_class($e),
                'message' => mb_substr($e->getMessage(), 0, 160),
            ]);
        }
    }

    /**
     * @return array<string,mixed>
     */
    private function call(string $endpoint, array $payload): array
    {
        $baseUrl = rtrim((string) Config::get('AI_PYTHON_URL', ''), '/');
        $secret = (string) Config::get('AI_PYTHON_SECRET', (string) Config::get('AI_API_KEY', ''));
        if ($baseUrl === '' || $secret === '') {
            throw new AiProviderException('The Python AI platform is not configured.');
        }
        if (Config::isProduction() && stripos($baseUrl, 'https://') !== 0) {
            throw new AiProviderException('The Python AI platform must use HTTPS in production.');
        }
        $body = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        if ($body === false) {
            throw new AiProviderException('The AI relay request could not be encoded.');
        }
        $url = $baseUrl . $endpoint;
        $headers = [
            'Content-Type: application/json',
            'Accept: application/json',
            'Authorization: Bearer ' . $secret,
        ];
        $timeout = min(60, max(5, (int) Config::get('AI_PYTHON_TIMEOUT', 45)));
        $started = microtime(true);

        [$raw, $status, $error] = $this->request($url, 'POST', $headers, $body, $timeout);

        FileLogger::write('ai_generation', [
            'type' => 'python_bridge_call',
            'endpoint' => $endpoint,
            'http_status' => (int) $status,
            'duration_ms' => (int) round((microtime(true) - $started) * 1000),
        ]);

        if ($raw === false || $error !== '') {
            throw new AiProviderException('The Python AI platform did not respond.');
        }
        $decoded = json_decode((string) $raw, true);
        if (!is_array($decoded) || (int) $status < 200 || (int) $status >= 300 || (($decoded['success'] ?? null) === false)) {
            throw new AiProviderException('The Python AI platform rejected the request.');
        }
        $data = $decoded['data'] ?? null;
        if (!is_array($data)) {
            throw new AiProviderException('The Python AI platform returned an unusable response.');
        }
        return $data;
    }

    /**
     * Open the assistant stream and hand each raw chunk to $onChunk as it
     * arrives, instead of waiting for the whole body.
     *
     * The caller must have already flushed its own response headers; this
     * exists purely so the browser sees the answer being written rather than
     * receiving one JSON body at the end (which is what made long answers feel
     * like a frozen page).
     *
     * @param callable(string): void $onChunk
     * @return array{0:bool,1:int} [completed, httpStatus]
     */
    public function streamAssist(array $context, string $question, callable $onChunk, int $timeout = 0): array
    {
        $baseUrl = rtrim((string) Config::get('AI_PYTHON_URL', ''), '/');
        $secret = (string) Config::get('AI_PYTHON_SECRET', (string) Config::get('AI_API_KEY', ''));
        if ($baseUrl === '' || $secret === '') {
            throw new AiProviderException('The Python AI platform is not configured.');
        }
        if (Config::isProduction() && stripos($baseUrl, 'https://') !== 0) {
            throw new AiProviderException('The Python AI platform must use HTTPS in production.');
        }
        $body = json_encode(
            ['context' => $context, 'question' => $question],
            JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
        );
        if ($body === false) {
            throw new AiProviderException('The AI relay request could not be encoded.');
        }

        $timeout = $timeout > 0 ? $timeout : (int) Config::get('AI_PYTHON_TIMEOUT', 45);
        // Shared hosting caps a request with max_execution_time; detect it at
        // runtime instead of assuming any particular host configuration. The
        // stream must finish inside the host limit, never rely on editing
        // php.ini.
        $executionLimit = (int) ini_get('max_execution_time');
        if ($executionLimit > 0) {
            $timeout = min($timeout, max(10, $executionLimit - 5));
        }
        $url = $baseUrl . '/api/agents/assist/stream';
        $headers = [
            'Content-Type: application/json',
            'Accept: text/event-stream',
            'Authorization: Bearer ' . $secret,
            'Cache-Control: no-cache',
        ];

        $started = microtime(true);
        $completed = false;
        $status = 0;

        if (function_exists('curl_init')) {
            $ch = curl_init($url);
            curl_setopt_array($ch, [
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => $body,
                CURLOPT_HTTPHEADER => $headers,
                CURLOPT_RETURNTRANSFER => false,
                CURLOPT_WRITEFUNCTION => static function ($handle, string $chunk) use ($onChunk): int {
                    $onChunk($chunk);
                    return strlen($chunk);
                },
                CURLOPT_CONNECTTIMEOUT => 10,
                CURLOPT_TIMEOUT => max(10, min(180, $timeout + 15)),
                CURLOPT_SSL_VERIFYPEER => true,
                CURLOPT_SSL_VERIFYHOST => 2,
                CURLOPT_NOSIGNAL => true,
            ]);
            $completed = curl_exec($ch) !== false;
            $status = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
            curl_close($ch);
        } else {
            // The Apache runtime may not load the cURL extension (extensions
            // are runtime capabilities, never Composer packages), but the
            // buffered relay already proves plain PHP streams reach the
            // platform. fopen() + fread() streams incrementally, so the
            // browser still sees words as they are produced.
            $context = stream_context_create([
                'http' => [
                    'method' => 'POST',
                    'header' => implode("\r\n", $headers),
                    'content' => $body,
                    'timeout' => max(10, min(180, $timeout + 15)),
                    'ignore_errors' => true,
                    'protocol_version' => 1.1,
                ],
                'ssl' => [
                    'verify_peer' => true,
                    'verify_peer_name' => true,
                    'allow_self_signed' => false,
                ],
            ]);
            $stream = @fopen($url, 'rb', false, $context);
            if ($stream === false) {
                throw new AiProviderException('The Python AI platform did not respond.');
            }
            try {
                while (!feof($stream)) {
                    $chunk = fread($stream, 8192);
                    if ($chunk === false || $chunk === '') {
                        continue;
                    }
                    $onChunk($chunk);
                }
                $completed = true;
                foreach ((stream_get_meta_data($stream)['wrapper_data'] ?? []) as $responseHeader) {
                    if (preg_match('/^HTTP\/\S+\s+(\d{3})/', (string) $responseHeader, $match)) {
                        $status = (int) $match[1];
                        break;
                    }
                }
            } finally {
                fclose($stream);
            }
        }

        FileLogger::write('ai_generation', [
            'type' => 'python_bridge_stream',
            'duration_ms' => (int) round((microtime(true) - $started) * 1000),
            'http_status' => $status,
            'completed' => $completed,
            'transport' => function_exists('curl_init') ? 'curl' : 'stream',
        ]);

        return [$completed, $status];
    }

    /**
     * @return array{0:string|false,1:int,2:string}
     */
    private function request(string $url, string $method, array $headers, string $body, int $timeout): array
    {
        if ($this->transport !== null) {
            $result = call_user_func($this->transport, $url, $method, $headers, $body, $timeout);
            return [is_string($result[0] ?? null) ? $result[0] : false, (int) ($result[1] ?? 0), (string) ($result[2] ?? '')];
        }
        if (!function_exists('curl_init')) {
            $context = stream_context_create([
                'http' => [
                    'method' => $method,
                    'header' => implode("\r\n", $headers),
                    'content' => $body,
                    'timeout' => $timeout,
                    'ignore_errors' => true,
                    'protocol_version' => 1.1,
                ],
                'ssl' => ['verify_peer' => true, 'verify_peer_name' => true, 'allow_self_signed' => false],
            ]);
            $raw = @file_get_contents($url, false, $context);
            $status = 0;
            foreach (($http_response_header ?? []) as $responseHeader) {
                if (preg_match('/^HTTP\/\S+\s+(\d{3})/', (string) $responseHeader, $match)) {
                    $status = (int) $match[1];
                    break;
                }
            }
            return [$raw === false ? false : $raw, $status, $raw === false ? 'stream HTTPS request failed' : ''];
        }
        $ch = curl_init($url);
        if ($ch === false) {
            return [false, 0, 'curl unavailable'];
        }
        curl_setopt_array($ch, [
            CURLOPT_CUSTOMREQUEST => $method,
            CURLOPT_POSTFIELDS => $body,
            CURLOPT_HTTPHEADER => $headers,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_TIMEOUT => $timeout,
            CURLOPT_SSL_VERIFYPEER => true,
            CURLOPT_SSL_VERIFYHOST => 2,
        ]);
        $raw = curl_exec($ch);
        $error = curl_error($ch);
        $status = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        return [$raw, $status, $error];
    }
}
