/**
 * PrintManager - Professional Printing System for Kingsway Academy
 * 
 * A content-aware printing system that generates clean, professional reports
 * without including application shell elements.
 * 
 * Features:
 * - Table reports with headers/footers
 * - Record/detail reports
 * - Modal content printing
 * - ID card printing
 * - Receipt printing
 * - Configurable paper size and orientation
 * - Professional report headers/footers
 * 
 * @author Kingsway Academy IT Team
 * @version 1.0.0
 */

const PrintManager = (function() {
    'use strict';

    // Default configuration
    const defaults = {
        schoolName: 'KINGSWAY PREPARATORY ACADEMY',
        schoolAddress: 'P.O. Box 12345, Nairobi, Kenya',
        schoolPhone: '+254 700 000 000',
        schoolEmail: 'info@kingswayacademy.ac.ke',
        schoolWebsite: 'www.kingswayacademy.ac.ke',
        appBase: window.APP_BASE || '',
        defaultPaperSize: 'A4',
        defaultOrientation: 'portrait'
    };

    /**
     * Escape HTML to prevent XSS
     */
    function escapeHtml(text) {
        if (text === null || text === undefined) return '';
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }

    /**
     * Format date for reports
     */
    function formatDate(date) {
        if (!date) return '';
        const d = new Date(date);
        if (isNaN(d.getTime())) return escapeHtml(date);
        return d.toLocaleDateString('en-GB', {
            day: '2-digit',
            month: 'long',
            year: 'numeric'
        });
    }

    /**
     * Format date/time for reports
     */
    function formatDateTime(date) {
        if (!date) return '';
        const d = new Date(date);
        if (isNaN(d.getTime())) return escapeHtml(date);
        return d.toLocaleDateString('en-GB', {
            day: '2-digit',
            month: 'long',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    }

    /**
     * Get current user info from AuthContext
     */
    function getCurrentUser() {
        if (window.AuthContext && typeof window.AuthContext.getUser === 'function') {
            return window.AuthContext.getUser();
        }
        return { username: 'System', full_name: 'System User' };
    }

    /**
     * Generate report header HTML
     */
    function generateReportHeader(options) {
        const config = { ...defaults, ...options };
        const user = getCurrentUser();
        
        return `
            <div class="print-report-header">
                <div class="print-school-info">
                    <h1 class="print-school-name">${escapeHtml(config.schoolName)}</h1>
                    <div class="print-school-details">
                        <p>${escapeHtml(config.schoolAddress)}</p>
                        <p>Phone: ${escapeHtml(config.schoolPhone)} | Email: ${escapeHtml(config.schoolEmail)}</p>
                        ${config.schoolWebsite ? `<p>Website: ${escapeHtml(config.schoolWebsite)}</p>` : ''}
                    </div>
                </div>
                <div class="print-report-title">
                    <h2>${escapeHtml(config.title)}</h2>
                    ${config.subtitle ? `<h3>${escapeHtml(config.subtitle)}</h3>` : ''}
                </div>
                <div class="print-report-meta">
                    <div class="print-report-filters">
                        ${config.filters ? Object.entries(config.filters).map(([key, value]) => 
                            value ? `<p><strong>${escapeHtml(key)}:</strong> ${escapeHtml(value)}</p>` : ''
                        ).join('') : ''}
                    </div>
                    <div class="print-report-dates">
                        <p><strong>Report Date:</strong> ${formatDate(new Date())}</p>
                        <p><strong>Generated By:</strong> ${escapeHtml(user.full_name || user.username)}</p>
                        ${config.reportCode ? `<p><strong>Report Code:</strong> ${escapeHtml(config.reportCode)}</p>` : ''}
                    </div>
                </div>
            </div>
        `;
    }

    /**
     * Generate report footer HTML
     */
    function generateReportFooter(options) {
        const config = { ...defaults, ...options };
        
        return `
            <div class="print-report-footer">
                <div class="print-footer-divider"></div>
                <div class="print-footer-content">
                    <div class="print-footer-left">
                        <p>${escapeHtml(config.schoolName)}</p>
                        <p class="print-footer-note">${config.confidentialityNote || 'This document is confidential and intended for authorized use only.'}</p>
                    </div>
                    <div class="print-footer-right">
                        <p>Printed: ${formatDateTime(new Date())}</p>
                        <p>Page <span class="page-number"></span> of <span class="total-pages"></span></p>
                    </div>
                </div>
                ${config.signatureSection ? `
                    <div class="print-signatures">
                        ${config.signatureSection.map(sig => `
                            <div class="print-signature-block">
                                <div class="signature-line"></div>
                                <p>${escapeHtml(sig.label)}</p>
                            </div>
                        `).join('')}
                    </div>
                ` : ''}
            </div>
        `;
    }

    /**
     * Generate print CSS
     */
    function generatePrintCSS(options) {
        const config = { ...defaults, ...options };
        const orientation = config.orientation || 'portrait';
        const paperSize = config.paperSize || 'A4';
        
        return `
            <style>
                @page {
                    size: ${paperSize} ${orientation};
                    margin: 12mm;
                }
                
                * {
                    -webkit-print-color-adjust: exact !important;
                    print-color-adjust: exact !important;
                }
                
                body {
                    font-family: 'Times New Roman', Times, serif;
                    font-size: 12pt;
                    line-height: 1.4;
                    color: #000;
                    background: #fff;
                    margin: 0;
                    padding: 0;
                }
                
                .print-report-header {
                    text-align: center;
                    margin-bottom: 20px;
                    padding-bottom: 15px;
                    border-bottom: 2px solid #000;
                }
                
                .print-school-name {
                    font-size: 18pt;
                    font-weight: bold;
                    margin: 0 0 5px 0;
                    text-transform: uppercase;
                }
                
                .print-school-details {
                    font-size: 10pt;
                    margin: 5px 0;
                }
                
                .print-school-details p {
                    margin: 2px 0;
                }
                
                .print-report-title h2 {
                    font-size: 14pt;
                    font-weight: bold;
                    margin: 15px 0 5px 0;
                }
                
                .print-report-title h3 {
                    font-size: 12pt;
                    font-weight: normal;
                    margin: 5px 0;
                }
                
                .print-report-meta {
                    display: flex;
                    justify-content: space-between;
                    margin-top: 15px;
                    font-size: 10pt;
                }
                
                .print-report-filters,
                .print-report-dates {
                    text-align: left;
                }
                
                .print-report-filters p,
                .print-report-dates p {
                    margin: 2px 0;
                }
                
                .print-report-summary {
                    background: #f5f5f5;
                    border: 1px solid #000;
                    padding: 10px;
                    margin: 15px 0;
                }
                
                .print-report-summary h4 {
                    font-size: 11pt;
                    margin: 0 0 10px 0;
                }
                
                .print-summary-grid {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
                    gap: 10px;
                }
                
                .print-summary-item {
                    padding: 5px;
                    background: #fff;
                    border: 1px solid #ccc;
                }
                
                .print-summary-label {
                    font-size: 9pt;
                    color: #666;
                }
                
                .print-summary-value {
                    font-size: 11pt;
                    font-weight: bold;
                }
                
                .print-table-container {
                    margin: 15px 0;
                }
                
                .print-table {
                    width: 100%;
                    border-collapse: collapse;
                    font-size: 10pt;
                }
                
                .print-table thead {
                    display: table-header-group;
                }
                
                .print-table tfoot {
                    display: table-footer-group;
                }
                
                .print-table th,
                .print-table td {
                    border: 1px solid #000;
                    padding: 6px 8px;
                    text-align: left;
                }
                
                .print-table th {
                    background: #f0f0f0;
                    font-weight: bold;
                    font-size: 10pt;
                }
                
                .print-table tbody tr {
                    break-inside: avoid;
                    page-break-inside: avoid;
                }
                
                .print-table tbody tr:nth-child(even) {
                    background: #f9f9f9;
                }
                
                .print-record-section {
                    margin: 15px 0;
                    padding: 10px;
                    border: 1px solid #000;
                    break-inside: avoid;
                    page-break-inside: avoid;
                }
                
                .print-record-section h4 {
                    font-size: 11pt;
                    margin: 0 0 10px 0;
                    border-bottom: 1px solid #000;
                    padding-bottom: 5px;
                }
                
                .print-record-row {
                    display: flex;
                    margin: 5px 0;
                }
                
                .print-record-label {
                    font-weight: bold;
                    width: 150px;
                    flex-shrink: 0;
                }
                
                .print-record-value {
                    flex-grow: 1;
                }
                
                .print-report-footer {
                    margin-top: 30px;
                    padding-top: 15px;
                    border-top: 1px solid #000;
                }
                
                .print-footer-divider {
                    border-bottom: 1px solid #000;
                    margin-bottom: 10px;
                }
                
                .print-footer-content {
                    display: flex;
                    justify-content: space-between;
                    font-size: 9pt;
                }
                
                .print-footer-note {
                    font-style: italic;
                    margin-top: 5px;
                }
                
                .print-signatures {
                    display: flex;
                    justify-content: space-around;
                    margin-top: 30px;
                }
                
                .print-signature-block {
                    text-align: center;
                    width: 200px;
                }
                
                .signature-line {
                    border-bottom: 1px solid #000;
                    height: 40px;
                    margin-bottom: 5px;
                }
                
                .print-no-records {
                    text-align: center;
                    padding: 20px;
                    font-style: italic;
                    color: #666;
                }
                
                .print-badge {
                    display: inline-block;
                    padding: 2px 6px;
                    border: 1px solid #000;
                    font-size: 9pt;
                    background: #fff;
                }
                
                /* Receipt-specific styles */
                .print-receipt {
                    max-width: 80mm;
                    margin: 0 auto;
                    font-family: 'Courier New', monospace;
                    font-size: 10pt;
                }
                
                .print-receipt-header {
                    text-align: center;
                    margin-bottom: 15px;
                }
                
                .print-receipt-header h1 {
                    font-size: 12pt;
                    margin: 0;
                }
                
                .print-receipt-divider {
                    border-bottom: 1px dashed #000;
                    margin: 10px 0;
                }
                
                .print-receipt-total {
                    font-size: 12pt;
                    font-weight: bold;
                    text-align: right;
                    margin-top: 10px;
                }
                
                /* ID card-specific styles */
                .print-id-card {
                    width: 3.375in;
                    height: 2.125in;
                    border: 1px solid #000;
                    page-break-after: always;
                    overflow: hidden;
                }
                
                @media print {
                    body {
                        margin: 0;
                    }
                }
            </style>
        `;
    }

    /**
     * Create print window and render content
     */
    function createPrintWindow(html, options) {
        const config = { ...defaults, ...options };
        
        // Create print window
        const printWindow = window.open('', '_blank');
        if (!printWindow) {
            alert('Please allow popups for printing functionality');
            return null;
        }
        
        // Generate complete HTML document
        const printDocument = `
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>${escapeHtml(config.title || 'Print')}</title>
                ${generatePrintCSS(config)}
            </head>
            <body>
                ${html}
                ${generateReportFooter(config)}
            </body>
            </html>
        `;
        
        printWindow.document.write(printDocument);
        printWindow.document.close();
        
        // Wait for content to load, then print
        printWindow.onload = function() {
            setTimeout(() => {
                printWindow.print();
                // Don't close automatically - let user review
                // printWindow.close();
            }, 250);
        };
        
        return printWindow;
    }

    /**
     * Print a table report
     */
    function printTable(options) {
        const config = {
            columns: [],
            rows: [],
            summary: null,
            ...options
        };
        
        if (!config.rows || config.rows.length === 0) {
            alert('No data to print');
            return;
        }
        
        // Generate table HTML
        const tableHtml = `
            <div class="print-table-container">
                <table class="print-table">
                    <thead>
                        <tr>
                            ${config.columns.map(col => 
                                `<th>${escapeHtml(col.label || col)}</th>`
                            ).join('')}
                        </tr>
                    </thead>
                    <tbody>
                        ${config.rows.map((row, index) => `
                            <tr>
                                <td>${index + 1}</td>
                                ${config.columns.slice(1).map(col => 
                                    `<td>${escapeHtml(row[col.key] || row[col] || '')}</td>`
                                ).join('')}
                            </tr>
                        `).join('')}
                    </tbody>
                </table>
            </div>
        `;
        
        // Generate summary if provided
        let summaryHtml = '';
        if (config.summary) {
            summaryHtml = `
                <div class="print-report-summary">
                    <h4>Summary</h4>
                    <div class="print-summary-grid">
                        ${Object.entries(config.summary).map(([key, value]) => `
                            <div class="print-summary-item">
                                <div class="print-summary-label">${escapeHtml(key)}</div>
                                <div class="print-summary-value">${escapeHtml(String(value))}</div>
                            </div>
                        `).join('')}
                    </div>
                </div>
            `;
        }
        
        // Generate complete HTML
        const html = `
            ${generateReportHeader(config)}
            ${summaryHtml}
            ${tableHtml}
        `;
        
        return createPrintWindow(html, config);
    }

    /**
     * Print a record/detail report
     */
    function printRecord(options) {
        const config = {
            sections: [],
            ...options
        };
        
        if (!config.sections || config.sections.length === 0) {
            alert('No data to print');
            return;
        }
        
        // Generate sections HTML
        const sectionsHtml = config.sections.map(section => `
            <div class="print-record-section">
                <h4>${escapeHtml(section.title)}</h4>
                ${section.fields ? section.fields.map(field => `
                    <div class="print-record-row">
                        <div class="print-record-label">${escapeHtml(field.label)}:</div>
                        <div class="print-record-value">${escapeHtml(String(field.value || ''))}</div>
                    </div>
                `).join('') : ''}
                ${section.content ? `<div>${escapeHtml(section.content)}</div>` : ''}
            </div>
        `).join('');
        
        // Generate complete HTML
        const html = `
            ${generateReportHeader(config)}
            ${sectionsHtml}
        `;
        
        return createPrintWindow(html, config);
    }

    /**
     * Print modal content
     */
    function printModal(modalId, options) {
        const modal = document.getElementById(modalId);
        if (!modal) {
            alert('Modal not found');
            return;
        }
        
        // Extract modal content
        const modalBody = modal.querySelector('.modal-body');
        if (!modalBody) {
            alert('Modal body not found');
            return;
        }
        
        const config = {
            title: options.title || modal.querySelector('.modal-title')?.textContent || 'Details',
            ...options
        };
        
        // Clean up modal content for printing
        const content = modalBody.innerHTML
            .replace(/<button[^>]*>.*?<\/button>/gi, '') // Remove buttons
            .replace(/<input[^>]*>/gi, '') // Remove inputs
            .replace(/<select[^>]*>.*?<\/select>/gi, '') // Remove selects
            .replace(/class="[^"]*btn[^"]*"/gi, 'class="print-hidden"') // Mark buttons
            .replace(/class="[^"]*form-control[^"]*"/gi, 'class="print-static"'); // Make forms static
        
        // Generate complete HTML
        const html = `
            ${generateReportHeader(config)}
            <div class="print-record-section">
                ${content}
            </div>
        `;
        
        return createPrintWindow(html, config);
    }

    /**
     * Print an arbitrary element
     */
    function printElement(elementId, options) {
        const element = document.getElementById(elementId);
        if (!element) {
            alert('Element not found');
            return;
        }
        
        const config = {
            title: options.title || 'Report',
            ...options
        };
        
        // Generate complete HTML
        const html = `
            ${generateReportHeader(config)}
            <div class="print-record-section">
                ${element.innerHTML}
            </div>
        `;
        
        return createPrintWindow(html, config);
    }

    /**
     * Print ID card
     */
    function printIdCard(options) {
        const config = {
            front: null,
            back: null,
            ...options
        };
        
        if (!config.front) {
            alert('ID card front required');
            return;
        }
        
        // Generate ID card HTML
        const cardsHtml = `
            <div class="print-id-card">
                ${config.front}
            </div>
            ${config.back ? `
                <div class="print-id-card">
                    ${config.back}
                </div>
            ` : ''}
        `;
        
        // ID cards use special paper size
        const idConfig = {
            ...config,
            paperSize: 'custom',
            orientation: 'portrait'
        };
        
        return createPrintWindow(cardsHtml, idConfig);
    }

    /**
     * Print receipt
     */
    function printReceipt(options) {
        const config = {
            items: [],
            total: 0,
            ...options
        };
        
        // Generate receipt HTML
        const itemsHtml = config.items.map(item => `
            <div class="print-receipt-item">
                <span>${escapeHtml(item.name)}</span>
                <span>${escapeHtml(String(item.price || item.amount || ''))}</span>
            </div>
        `).join('');
        
        const receiptHtml = `
            <div class="print-receipt">
                <div class="print-receipt-header">
                    <h1>${escapeHtml(config.schoolName)}</h1>
                    <p>${escapeHtml(config.schoolAddress)}</p>
                </div>
                <div class="print-receipt-divider"></div>
                <div>
                    <p><strong>Receipt No:</strong> ${escapeHtml(config.receiptNumber || '')}</p>
                    <p><strong>Date:</strong> ${formatDate(config.date)}</p>
                    <p><strong>Customer:</strong> ${escapeHtml(config.customer || '')}</p>
                </div>
                <div class="print-receipt-divider"></div>
                <div>
                    ${itemsHtml}
                </div>
                <div class="print-receipt-divider"></div>
                <div class="print-receipt-total">
                    <p>TOTAL: ${escapeHtml(String(config.total))}</p>
                </div>
                <div class="print-receipt-divider"></div>
                <p style="text-align: center; font-size: 9pt;">Thank you for your business!</p>
            </div>
        `;
        
        // Receipts use special paper size
        const receiptConfig = {
            ...config,
            paperSize: '80mm auto',
            orientation: 'portrait'
        };
        
        return createPrintWindow(receiptHtml, receiptConfig);
    }

    /**
     * Print certificate
     */
    function printCertificate(options) {
        const config = {
            type: 'academic_excellence',
            recipientName: '',
            achievement: '',
            academicYear: '',
            sport: '',
            course: '',
            certificateNumber: '',
            dateAwarded: new Date().toLocaleDateString(),
            ...options
        };
        
        // Determine template based on certificate type
        const templateUrls = {
            'academic_excellence': 'templates/certificates/academic_excellence.php',
            'sports_achievement': 'templates/certificates/sports_achievement.php',
            'graduation': 'templates/certificates/graduation.php'
        };
        
        const templateUrl = templateUrls[config.type] || templateUrls['academic_excellence'];
        const appBase = window.APP_BASE || '';
        
        // Open certificate in new window
        const printWindow = window.open('', '_blank');
        if (!printWindow) {
            alert('Please allow popups for certificate printing');
            return;
        }
        
        // Load certificate template with school config
        printWindow.location.href = `${appBase}/${templateUrl}?` + new URLSearchParams({
            schoolName: window.SCHOOL_CONFIG?.name || 'Kingsway Preparatory School',
            schoolMotto: window.SCHOOL_CONFIG?.motto || 'In God We Soar',
            schoolLogo: window.SCHOOL_CONFIG?.logo || `${appBase}/images/logo.jpg`,
            schoolAddress: window.SCHOOL_CONFIG?.address || 'P.O Box 203-20203, Londiani, Kenya',
            schoolPhone: window.SCHOOL_CONFIG?.phone || '+254-720-113030 / +254-720-113031',
            schoolEmail: window.SCHOOL_CONFIG?.email || 'info@kingswaypreparatoryschool.sc.ke',
            schoolWebsite: window.SCHOOL_CONFIG?.website || 'www.kingswaypreparatoryschool.sc.ke',
            principalName: window.SCHOOL_CONFIG?.principal || 'Mr Bett Junior',
            principalTitle: window.SCHOOL_CONFIG?.principalTitle || 'Headteacher',
            recipientName: config.recipientName,
            achievement: config.achievement,
            academicYear: config.academicYear,
            sport: config.sport || '',
            course: config.course || '',
            certificateNumber: config.certificateNumber,
            dateAwarded: config.dateAwarded,
            teacherName: config.teacherName || 'Class Teacher',
            sportsCoordinatorName: config.sportsCoordinatorName || 'Sports Coordinator',
            examOfficerName: config.examOfficerName || 'Examinations Officer'
        });
    }

    /**
     * Export data to CSV
     */
    function exportToCSV(options) {
        const config = {
            columns: [],
            rows: [],
            filename: 'export',
            ...options
        };
        
        if (!config.rows || config.rows.length === 0) {
            alert('No data to export');
            return;
        }
        
        // Generate CSV content
        const headers = config.columns.map(col => `"${String(col.label || col).replace(/"/g, '""')}"`);
        const rows = config.rows.map(row => 
            config.columns.map(col => 
                `"${String(row[col.key] || row[col] || '').replace(/"/g, '""')}"`
            )
        );
        
        const csv = [headers, ...rows].map(row => row.join(',')).join('\n');
        
        // Create download
        const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${config.filename}_${new Date().toISOString().slice(0, 10)}.csv`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    // Public API
    return {
        printTable,
        printRecord,
        printModal,
        printElement,
        printIdCard,
        printReceipt,
        printCertificate,
        exportToCSV,
        setDefaults: function(newDefaults) {
            Object.assign(defaults, newDefaults);
        }
    };

})();

// Make available globally
window.PrintManager = PrintManager;
