<?php
/**
 * Print Report Header Template
 * 
 * Standard header for all printed reports
 * 
 * @var string $schoolName School name
 * @var string $schoolAddress School address
 * @var string $schoolPhone School phone number
 * @var string $schoolEmail School email
 * @var string $schoolWebsite School website
 * @var string $title Report title
 * @var string $subtitle Report subtitle (optional)
 * @var array $filters Applied filters (optional)
 * @var string $reportCode Report reference code (optional)
 * @var string $generatedBy User who generated the report (optional)
 * @var string $generatedAt Report generation timestamp (optional)
 */

$schoolName = $schoolName ?? 'KINGSWAY PREPARATORY ACADEMY';
$schoolAddress = $schoolAddress ?? 'P.O. Box 12345, Nairobi, Kenya';
$schoolPhone = $schoolPhone ?? '+254 700 000 000';
$schoolEmail = $schoolEmail ?? 'info@kingswayacademy.ac.ke';
$schoolWebsite = $schoolWebsite ?? 'www.kingswayacademy.ac.ke';
$generatedBy = $generatedBy ?? 'System';
$generatedAt = $generatedAt ?? date('d F Y H:i');
?>

<div class="print-report-header">
    <div class="print-school-info">
        <h1 class="print-school-name"><?php echo htmlspecialchars($schoolName); ?></h1>
        <div class="print-school-details">
            <p><?php echo htmlspecialchars($schoolAddress); ?></p>
            <p>Phone: <?php echo htmlspecialchars($schoolPhone); ?> | Email: <?php echo htmlspecialchars($schoolEmail); ?></p>
            <?php if ($schoolWebsite): ?>
                <p>Website: <?php echo htmlspecialchars($schoolWebsite); ?></p>
            <?php endif; ?>
        </div>
    </div>
    
    <div class="print-report-title">
        <h2><?php echo htmlspecialchars($title); ?></h2>
        <?php if ($subtitle): ?>
            <h3><?php echo htmlspecialchars($subtitle); ?></h3>
        <?php endif; ?>
    </div>
    
    <div class="print-report-meta">
        <div class="print-report-filters">
            <?php if ($filters && is_array($filters)): ?>
                <?php foreach ($filters as $key => $value): ?>
                    <?php if ($value): ?>
                        <p><strong><?php echo htmlspecialchars($key); ?>:</strong> <?php echo htmlspecialchars($value); ?></p>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        
        <div class="print-report-dates">
            <p><strong>Report Date:</strong> <?php echo htmlspecialchars($generatedAt); ?></p>
            <p><strong>Generated By:</strong> <?php echo htmlspecialchars($generatedBy); ?></p>
            <?php if ($reportCode): ?>
                <p><strong>Report Code:</strong> <?php echo htmlspecialchars($reportCode); ?></p>
            <?php endif; ?>
        </div>
    </div>
</div>
