-- =============================================================================
-- Sidebar-Driven Permission Grant
-- Auto-generated 2026-04-26 15:57:17
-- Ensures every role has the permissions matching role_sidebars.php
-- =============================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- ─── INSERT all required permission codes ─────────────────────────────────
INSERT IGNORE INTO permissions (code, module, description) VALUES ('system_view', 'system', 'Auto-granted: system_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('system_manage', 'system', 'Auto-granted: system_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('system_admin', 'system', 'Auto-granted: system_admin');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('users_view', 'users', 'Auto-granted: users_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('users_create', 'users', 'Auto-granted: users_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('users_update', 'users', 'Auto-granted: users_update');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('users_delete', 'users', 'Auto-granted: users_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('schoolconfig_view', 'schoolconfig', 'Auto-granted: schoolconfig_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('schoolconfig_update', 'schoolconfig', 'Auto-granted: schoolconfig_update');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('students_view', 'students', 'Auto-granted: students_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('students_create', 'students', 'Auto-granted: students_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('students_update', 'students', 'Auto-granted: students_update');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('students_delete', 'students', 'Auto-granted: students_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('students_manage', 'students', 'Auto-granted: students_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('students_admin', 'students', 'Auto-granted: students_admin');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_view', 'admission', 'Auto-granted: admission_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_create', 'admission', 'Auto-granted: admission_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_edit', 'admission', 'Auto-granted: admission_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_approve', 'admission', 'Auto-granted: admission_approve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_manage', 'admission', 'Auto-granted: admission_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_applications_create', 'admission_applications', 'Auto-granted: admission_applications_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_applications_edit', 'admission_applications', 'Auto-granted: admission_applications_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_applications_approve_final', 'admission_applications', 'Auto-granted: admission_applications_approve_final');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_applications_generate', 'admission_applications', 'Auto-granted: admission_applications_generate');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_documents_upload', 'admission_documents', 'Auto-granted: admission_documents_upload');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_documents_verify', 'admission_documents', 'Auto-granted: admission_documents_verify');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_interviews_schedule', 'admission_interviews', 'Auto-granted: admission_interviews_schedule');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('admission_interviews_create', 'admission_interviews', 'Auto-granted: admission_interviews_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_view', 'staff', 'Auto-granted: staff_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_view_all', 'staff', 'Auto-granted: staff_view_all');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_view_department', 'staff', 'Auto-granted: staff_view_department');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_view_own', 'staff', 'Auto-granted: staff_view_own');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_view_directory', 'staff', 'Auto-granted: staff_view_directory');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_view_contacts', 'staff', 'Auto-granted: staff_view_contacts');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_create', 'staff', 'Auto-granted: staff_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_update', 'staff', 'Auto-granted: staff_update');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_edit', 'staff', 'Auto-granted: staff_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_delete', 'staff', 'Auto-granted: staff_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_manage', 'staff', 'Auto-granted: staff_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_admin', 'staff', 'Auto-granted: staff_admin');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('staff_approve', 'staff', 'Auto-granted: staff_approve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('fee_structure_view', 'fee_structure', 'Auto-granted: fee_structure_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('fee_structure_view_own', 'fee_structure', 'Auto-granted: fee_structure_view_own');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('fee_structure_view_financial', 'fee_structure', 'Auto-granted: fee_structure_view_financial');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('fees_view', 'fees', 'Auto-granted: fees_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('fee_structure_create', 'fee_structure', 'Auto-granted: fee_structure_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('fee_structure_edit', 'fee_structure', 'Auto-granted: fee_structure_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('fee_structure_delete', 'fee_structure', 'Auto-granted: fee_structure_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('fee_structure_manage', 'fee_structure', 'Auto-granted: fee_structure_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('fee_structure_admin', 'fee_structure', 'Auto-granted: fee_structure_admin');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('fee_structure_approve', 'fee_structure', 'Auto-granted: fee_structure_approve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_view', 'finance', 'Auto-granted: finance_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_view_all', 'finance', 'Auto-granted: finance_view_all');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_view_own', 'finance', 'Auto-granted: finance_view_own');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_create', 'finance', 'Auto-granted: finance_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_edit', 'finance', 'Auto-granted: finance_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_delete', 'finance', 'Auto-granted: finance_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_manage', 'finance', 'Auto-granted: finance_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_admin', 'finance', 'Auto-granted: finance_admin');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_approve', 'finance', 'Auto-granted: finance_approve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_approve_payments', 'finance', 'Auto-granted: finance_approve_payments');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('finance_export', 'finance', 'Auto-granted: finance_export');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('payroll_view', 'payroll', 'Auto-granted: payroll_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('payroll_view_own', 'payroll', 'Auto-granted: payroll_view_own');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('payroll_create', 'payroll', 'Auto-granted: payroll_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('payroll_edit', 'payroll', 'Auto-granted: payroll_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('payroll_manage', 'payroll', 'Auto-granted: payroll_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('payroll_approve', 'payroll', 'Auto-granted: payroll_approve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('attendance_view', 'attendance', 'Auto-granted: attendance_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('attendance_create', 'attendance', 'Auto-granted: attendance_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('attendance_edit', 'attendance', 'Auto-granted: attendance_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('attendance_manage', 'attendance', 'Auto-granted: attendance_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('academics_view', 'academics', 'Auto-granted: academics_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('academics_create', 'academics', 'Auto-granted: academics_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('academics_edit', 'academics', 'Auto-granted: academics_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('academics_delete', 'academics', 'Auto-granted: academics_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('academics_manage', 'academics', 'Auto-granted: academics_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('academics_approve', 'academics', 'Auto-granted: academics_approve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('schedules_view', 'schedules', 'Auto-granted: schedules_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('schedules_create', 'schedules', 'Auto-granted: schedules_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('schedules_update', 'schedules', 'Auto-granted: schedules_update');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('schedules_edit', 'schedules', 'Auto-granted: schedules_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('schedules_manage', 'schedules', 'Auto-granted: schedules_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('schedules_approve', 'schedules', 'Auto-granted: schedules_approve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('lesson_plans_view', 'lesson_plans', 'Auto-granted: lesson_plans_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('lesson_plans_create', 'lesson_plans', 'Auto-granted: lesson_plans_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('lesson_plans_edit', 'lesson_plans', 'Auto-granted: lesson_plans_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('lesson_plans_approve', 'lesson_plans', 'Auto-granted: lesson_plans_approve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('lesson_plans_manage', 'lesson_plans', 'Auto-granted: lesson_plans_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('assessments_view', 'assessments', 'Auto-granted: assessments_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('assessments_create', 'assessments', 'Auto-granted: assessments_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('assessments_edit', 'assessments', 'Auto-granted: assessments_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('assessments_delete', 'assessments', 'Auto-granted: assessments_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('assessments_manage', 'assessments', 'Auto-granted: assessments_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('assessments_approve', 'assessments', 'Auto-granted: assessments_approve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_view', 'discipline', 'Auto-granted: discipline_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_view_all', 'discipline', 'Auto-granted: discipline_view_all');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_view_own', 'discipline', 'Auto-granted: discipline_view_own');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_report', 'discipline', 'Auto-granted: discipline_report');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_create', 'discipline', 'Auto-granted: discipline_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_edit', 'discipline', 'Auto-granted: discipline_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_delete', 'discipline', 'Auto-granted: discipline_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_approve', 'discipline', 'Auto-granted: discipline_approve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_manage', 'discipline', 'Auto-granted: discipline_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_admin', 'discipline', 'Auto-granted: discipline_admin');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('discipline_resolve', 'discipline', 'Auto-granted: discipline_resolve');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('transport_view', 'transport', 'Auto-granted: transport_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('transport_create', 'transport', 'Auto-granted: transport_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('transport_update', 'transport', 'Auto-granted: transport_update');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('transport_edit', 'transport', 'Auto-granted: transport_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('transport_manage', 'transport', 'Auto-granted: transport_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('boarding_view', 'boarding', 'Auto-granted: boarding_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('boarding_view_all', 'boarding', 'Auto-granted: boarding_view_all');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('boarding_view_own', 'boarding', 'Auto-granted: boarding_view_own');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('boarding_create', 'boarding', 'Auto-granted: boarding_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('boarding_edit', 'boarding', 'Auto-granted: boarding_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('boarding_delete', 'boarding', 'Auto-granted: boarding_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('boarding_manage', 'boarding', 'Auto-granted: boarding_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('boarding_admin', 'boarding', 'Auto-granted: boarding_admin');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('boarding_assign', 'boarding', 'Auto-granted: boarding_assign');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('boarding_roll_call', 'boarding', 'Auto-granted: boarding_roll_call');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('activities_view', 'activities', 'Auto-granted: activities_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('activities_create', 'activities', 'Auto-granted: activities_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('activities_update', 'activities', 'Auto-granted: activities_update');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('activities_edit', 'activities', 'Auto-granted: activities_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('activities_manage', 'activities', 'Auto-granted: activities_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('communications_view', 'communications', 'Auto-granted: communications_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('communications_create', 'communications', 'Auto-granted: communications_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('communications_manage', 'communications', 'Auto-granted: communications_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('inventory_view', 'inventory', 'Auto-granted: inventory_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('inventory_create', 'inventory', 'Auto-granted: inventory_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('inventory_update', 'inventory', 'Auto-granted: inventory_update');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('inventory_edit', 'inventory', 'Auto-granted: inventory_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('inventory_delete', 'inventory', 'Auto-granted: inventory_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('inventory_manage', 'inventory', 'Auto-granted: inventory_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('library_view', 'library', 'Auto-granted: library_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('library_create', 'library', 'Auto-granted: library_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('library_edit', 'library', 'Auto-granted: library_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('library_delete', 'library', 'Auto-granted: library_delete');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('library_manage', 'library', 'Auto-granted: library_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('library_issue', 'library', 'Auto-granted: library_issue');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('health_view', 'health', 'Auto-granted: health_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('health_create', 'health', 'Auto-granted: health_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('health_edit', 'health', 'Auto-granted: health_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('health_manage', 'health', 'Auto-granted: health_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('counseling_view', 'counseling', 'Auto-granted: counseling_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('counseling_create', 'counseling', 'Auto-granted: counseling_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('counseling_edit', 'counseling', 'Auto-granted: counseling_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('counseling_manage', 'counseling', 'Auto-granted: counseling_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('chapel_view', 'chapel', 'Auto-granted: chapel_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('chapel_create', 'chapel', 'Auto-granted: chapel_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('chapel_edit', 'chapel', 'Auto-granted: chapel_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('chapel_manage', 'chapel', 'Auto-granted: chapel_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('catering_view', 'catering', 'Auto-granted: catering_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('catering_create', 'catering', 'Auto-granted: catering_create');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('catering_edit', 'catering', 'Auto-granted: catering_edit');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('catering_manage', 'catering', 'Auto-granted: catering_manage');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('reports_view', 'reports', 'Auto-granted: reports_view');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('reports_export', 'reports', 'Auto-granted: reports_export');
INSERT IGNORE INTO permissions (code, module, description) VALUES ('reports_manage', 'reports', 'Auto-granted: reports_manage');

-- ─── ASSIGN permissions to roles ──────────────────────────────────────────

-- Role 2
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'system_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'system_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'system_admin';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'users_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'users_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'users_update';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'users_delete';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'schoolconfig_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'schoolconfig_update';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'staff_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'finance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'reports_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'academics_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'schedules_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'assessments_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'inventory_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'library_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'transport_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'boarding_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'activities_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'discipline_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'counseling_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'health_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'chapel_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'catering_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'payroll_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'lesson_plans_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'admission_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 2, id FROM permissions WHERE code = 'fee_structure_view';

-- Role 3
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'students_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'admission_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'admission_applications_approve_final';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'admission_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'staff_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'staff_view_all';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'staff_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'staff_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'staff_admin';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'fee_structure_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'fee_structure_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'fee_structure_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'finance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'finance_view_all';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'finance_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'finance_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'finance_admin';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'finance_export';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'payroll_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'payroll_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'payroll_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'payroll_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'assessments_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'assessments_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'academics_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'academics_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'academics_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'schedules_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'schedules_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'schedules_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'lesson_plans_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'lesson_plans_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'discipline_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'discipline_view_all';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'discipline_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'discipline_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'transport_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'transport_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'boarding_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'boarding_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'activities_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'activities_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'communications_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'communications_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'inventory_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'inventory_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'library_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'library_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'reports_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'reports_export';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'reports_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'users_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 3, id FROM permissions WHERE code = 'schoolconfig_view';

-- Role 4
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_applications_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_applications_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_applications_approve_final';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_applications_generate';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_documents_upload';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_documents_verify';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_interviews_schedule';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'admission_interviews_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'students_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'students_update';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'students_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'students_admin';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'staff_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'staff_view_all';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'staff_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'staff_update';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'staff_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'staff_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'staff_admin';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'fee_structure_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'fees_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'finance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'finance_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'finance_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'finance_approve_payments';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'payroll_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'payroll_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'attendance_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'attendance_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'transport_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'transport_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'transport_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'boarding_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'boarding_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'academics_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'academics_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'academics_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'schedules_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'assessments_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'discipline_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'discipline_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'library_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'library_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'library_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'library_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'health_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'health_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'health_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'health_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'communications_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'communications_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'reports_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'inventory_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'activities_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'users_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'users_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 4, id FROM permissions WHERE code = 'users_update';

-- Role 5
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'admission_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'admission_interviews_schedule';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'admission_interviews_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'admission_applications_approve_final';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'academics_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'academics_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'academics_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'academics_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'assessments_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'assessments_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'assessments_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'staff_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'staff_view_all';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'staff_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'finance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'fee_structure_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'lesson_plans_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'lesson_plans_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'lesson_plans_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'schedules_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'schedules_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'schedules_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'discipline_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'discipline_view_all';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'discipline_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'communications_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'reports_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'reports_export';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'boarding_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'boarding_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'transport_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'students_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'library_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'library_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'health_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'health_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'counseling_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 5, id FROM permissions WHERE code = 'activities_view';

-- Role 6
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'attendance_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'assessments_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'assessments_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'assessments_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'assessments_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'academics_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'academics_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'academics_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'academics_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'lesson_plans_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'lesson_plans_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'lesson_plans_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'lesson_plans_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'lesson_plans_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'schedules_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'schedules_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'schedules_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'schedules_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'staff_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'staff_view_department';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'reports_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'library_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'payroll_view_own';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'discipline_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 6, id FROM permissions WHERE code = 'activities_view';

-- Role 7
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'attendance_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'lesson_plans_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'lesson_plans_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'lesson_plans_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'assessments_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'assessments_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'assessments_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'schedules_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'discipline_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'discipline_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'staff_view_directory';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'payroll_view_own';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 7, id FROM permissions WHERE code = 'reports_view';

-- Role 8
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'attendance_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'lesson_plans_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'lesson_plans_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'lesson_plans_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'assessments_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'assessments_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'assessments_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'schedules_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'staff_view_directory';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'payroll_view_own';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 8, id FROM permissions WHERE code = 'reports_view';

-- Role 9
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 9, id FROM permissions WHERE code = 'lesson_plans_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 9, id FROM permissions WHERE code = 'lesson_plans_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 9, id FROM permissions WHERE code = 'schedules_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 9, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 9, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 9, id FROM permissions WHERE code = 'students_view';

-- Role 10
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'fee_structure_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'fee_structure_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'fee_structure_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'fee_structure_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'fee_structure_view_financial';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'fee_structure_admin';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'fees_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'finance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'finance_view_all';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'finance_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'finance_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'finance_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'finance_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'finance_approve_payments';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'finance_export';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'payroll_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'payroll_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'payroll_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'payroll_approve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'admission_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'inventory_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'reports_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'reports_export';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 10, id FROM permissions WHERE code = 'staff_view';

-- Role 14
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'inventory_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'inventory_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'inventory_update';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'inventory_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'inventory_delete';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'inventory_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'library_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'library_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'library_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'library_delete';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'library_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'library_issue';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'catering_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'finance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 14, id FROM permissions WHERE code = 'communications_view';

-- Role 16
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 16, id FROM permissions WHERE code = 'catering_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 16, id FROM permissions WHERE code = 'catering_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 16, id FROM permissions WHERE code = 'catering_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 16, id FROM permissions WHERE code = 'catering_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 16, id FROM permissions WHERE code = 'inventory_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 16, id FROM permissions WHERE code = 'finance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 16, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 16, id FROM permissions WHERE code = 'students_view';

-- Role 18
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'boarding_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'boarding_view_all';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'boarding_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'boarding_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'boarding_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'boarding_assign';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'boarding_roll_call';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'health_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'health_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'health_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'health_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'attendance_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'communications_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 18, id FROM permissions WHERE code = 'reports_view';

-- Role 21
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 21, id FROM permissions WHERE code = 'activities_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 21, id FROM permissions WHERE code = 'activities_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 21, id FROM permissions WHERE code = 'activities_update';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 21, id FROM permissions WHERE code = 'activities_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 21, id FROM permissions WHERE code = 'activities_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 21, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 21, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 21, id FROM permissions WHERE code = 'communications_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 21, id FROM permissions WHERE code = 'reports_view';

-- Role 23
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 23, id FROM permissions WHERE code = 'transport_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 23, id FROM permissions WHERE code = 'attendance_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 23, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 23, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 23, id FROM permissions WHERE code = 'students_view';

-- Role 24
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'counseling_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'counseling_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'counseling_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'counseling_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'chapel_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'chapel_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'chapel_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'chapel_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'communications_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'health_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 24, id FROM permissions WHERE code = 'reports_view';

-- Role 32
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 32, id FROM permissions WHERE code = 'catering_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 32, id FROM permissions WHERE code = 'communications_view';

-- Role 33
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 33, id FROM permissions WHERE code = 'transport_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 33, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 33, id FROM permissions WHERE code = 'communications_view';

-- Role 34
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 34, id FROM permissions WHERE code = 'communications_view';

-- Role 63
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'discipline_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'discipline_view_all';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'discipline_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'discipline_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'discipline_manage';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'discipline_resolve';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'discipline_report';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'lesson_plans_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'lesson_plans_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'lesson_plans_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'assessments_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'assessments_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'assessments_edit';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'schedules_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'students_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'communications_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'communications_create';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'reports_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'counseling_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'library_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 63, id FROM permissions WHERE code = 'payroll_view_own';

-- Role 64
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 64, id FROM permissions WHERE code = 'schedules_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 64, id FROM permissions WHERE code = 'attendance_view';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 64, id FROM permissions WHERE code = 'payroll_view_own';
INSERT IGNORE INTO role_permissions (role_id, permission_id) SELECT 64, id FROM permissions WHERE code = 'communications_view';

SET FOREIGN_KEY_CHECKS = 1;
