-- Migration: Academic Module Missing Tables
-- Date: 2026-07-14
-- Description: Create missing database tables for Block 4 (Teaching Delivery)
-- Tables: schemes_of_work, teaching_materials, past_papers

-- ============================================================
-- Table: schemes_of_work
-- Purpose: Store teacher schemes of work for term planning
-- ============================================================
CREATE TABLE IF NOT EXISTS `schemes_of_work` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `teacher_id` INT UNSIGNED NOT NULL,
  `class_id` INT UNSIGNED NOT NULL,
  `stream_id` INT UNSIGNED DEFAULT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  `subject_name` VARCHAR(255) NOT NULL,
  `learning_area_id` INT UNSIGNED DEFAULT NULL,
  `academic_year_id` INT UNSIGNED NOT NULL,
  `term_id` INT UNSIGNED NOT NULL,
  `term_number` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `week_number` INT NOT NULL,
  `strand` VARCHAR(255) DEFAULT NULL,
  `sub_strand` VARCHAR(255) DEFAULT NULL,
  `learning_outcomes` TEXT,
  `key_vocabulary` TEXT,
  `resources` TEXT,
  `activities` TEXT,
  `assessment_methods` TEXT,
  `status` ENUM('draft', 'submitted', 'under_review', 'changes_requested', 'approved', 'in_progress', 'completed', 'archived') DEFAULT 'draft',
  `approved_by` INT UNSIGNED DEFAULT NULL,
  `approved_at` TIMESTAMP NULL DEFAULT NULL,
  `rejection_reason` TEXT,
  `file_path` VARCHAR(500) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_teacher_id` (`teacher_id`),
  KEY `idx_class_id` (`class_id`),
  KEY `idx_stream_id` (`stream_id`),
  KEY `idx_subject_id` (`subject_id`),
  KEY `idx_learning_area_id` (`learning_area_id`),
  KEY `idx_academic_year_id` (`academic_year_id`),
  KEY `idx_term_id` (`term_id`),
  KEY `idx_status` (`status`),
  KEY `idx_week_number` (`week_number`),
  KEY `idx_teacher_term_class` (`teacher_id`, `term_id`, `class_id`),
  KEY `fk_schemes_teacher` (`teacher_id`),
  KEY `fk_schemes_class` (`class_id`),
  KEY `fk_schemes_stream` (`stream_id`),
  KEY `fk_schemes_subject` (`subject_id`),
  KEY `fk_schemes_learning_area` (`learning_area_id`),
  KEY `fk_schemes_academic_year` (`academic_year_id`),
  KEY `fk_schemes_term` (`term_id`),
  KEY `fk_schemes_approved_by` (`approved_by`),
  CONSTRAINT `fk_schemes_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `staff` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_schemes_class` FOREIGN KEY (`class_id`) REFERENCES `classes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_schemes_stream` FOREIGN KEY (`stream_id`) REFERENCES `class_streams` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_schemes_subject` FOREIGN KEY (`subject_id`) REFERENCES `curriculum_units` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_schemes_learning_area` FOREIGN KEY (`learning_area_id`) REFERENCES `learning_areas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_schemes_academic_year` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_schemes_term` FOREIGN KEY (`term_id`) REFERENCES `academic_terms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_schemes_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `staff` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Table: teaching_materials
-- Purpose: Store teaching resources uploaded by teachers
-- ============================================================
CREATE TABLE IF NOT EXISTS `teaching_materials` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `subject_id` INT UNSIGNED DEFAULT NULL,
  `learning_area_id` INT UNSIGNED DEFAULT NULL,
  `teacher_id` INT UNSIGNED NOT NULL,
  `class_id` INT UNSIGNED DEFAULT NULL,
  `academic_year_id` INT UNSIGNED DEFAULT NULL,
  `term_id` INT UNSIGNED DEFAULT NULL,
  `file_path` VARCHAR(500) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `file_size` BIGINT UNSIGNED DEFAULT NULL,
  `resource_type` ENUM('document', 'presentation', 'video', 'audio', 'image', 'other') DEFAULT 'document',
  `access_scope` ENUM('private', 'subject', 'school', 'public') DEFAULT 'subject',
  `status` ENUM('pending', 'approved', 'rejected', 'archived') DEFAULT 'pending',
  `download_count` INT UNSIGNED DEFAULT 0,
  `uploaded_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_subject_id` (`subject_id`),
  KEY `idx_learning_area_id` (`learning_area_id`),
  KEY `idx_teacher_id` (`teacher_id`),
  KEY `idx_class_id` (`class_id`),
  KEY `idx_academic_year_id` (`academic_year_id`),
  KEY `idx_term_id` (`term_id`),
  KEY `idx_resource_type` (`resource_type`),
  KEY `idx_access_scope` (`access_scope`),
  KEY `idx_status` (`status`),
  KEY `idx_uploaded_at` (`uploaded_at`),
  KEY `fk_materials_subject` (`subject_id`),
  KEY `fk_materials_learning_area` (`learning_area_id`),
  KEY `fk_materials_teacher` (`teacher_id`),
  KEY `fk_materials_class` (`class_id`),
  KEY `fk_materials_academic_year` (`academic_year_id`),
  KEY `fk_materials_term` (`term_id`),
  CONSTRAINT `fk_materials_subject` FOREIGN KEY (`subject_id`) REFERENCES `curriculum_units` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_materials_learning_area` FOREIGN KEY (`learning_area_id`) REFERENCES `learning_areas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_materials_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `staff` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_materials_class` FOREIGN KEY (`class_id`) REFERENCES `classes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_materials_academic_year` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_materials_term` FOREIGN KEY (`term_id`) REFERENCES `academic_terms` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Table: past_papers
-- Purpose: Store past examination papers for reference
-- ============================================================
CREATE TABLE IF NOT EXISTS `past_papers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `subject_id` INT UNSIGNED DEFAULT NULL,
  `learning_area_id` INT UNSIGNED DEFAULT NULL,
  `exam_year` YEAR NOT NULL,
  `exam_type` ENUM('kcpe', 'kcse', 'mock', 'internal', 'other') DEFAULT 'internal',
  `term_id` INT UNSIGNED DEFAULT NULL,
  `academic_year_id` INT UNSIGNED DEFAULT NULL,
  `file_path` VARCHAR(500) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `file_size` BIGINT UNSIGNED DEFAULT NULL,
  `uploaded_by` INT UNSIGNED NOT NULL,
  `download_count` INT UNSIGNED DEFAULT 0,
  `status` ENUM('active', 'archived') DEFAULT 'active',
  `uploaded_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_subject_id` (`subject_id`),
  KEY `idx_learning_area_id` (`learning_area_id`),
  KEY `idx_exam_year` (`exam_year`),
  KEY `idx_exam_type` (`exam_type`),
  KEY `idx_term_id` (`term_id`),
  KEY `idx_academic_year_id` (`academic_year_id`),
  KEY `idx_uploaded_by` (`uploaded_by`),
  KEY `idx_status` (`status`),
  KEY `idx_uploaded_at` (`uploaded_at`),
  KEY `idx_exam_year_type` (`exam_year`, `exam_type`),
  KEY `fk_papers_subject` (`subject_id`),
  KEY `fk_papers_learning_area` (`learning_area_id`),
  KEY `fk_papers_term` (`term_id`),
  KEY `fk_papers_academic_year` (`academic_year_id`),
  KEY `fk_papers_uploaded_by` (`uploaded_by`),
  CONSTRAINT `fk_papers_subject` FOREIGN KEY (`subject_id`) REFERENCES `curriculum_units` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_papers_learning_area` FOREIGN KEY (`learning_area_id`) REFERENCES `learning_areas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_papers_term` FOREIGN KEY (`term_id`) REFERENCES `academic_terms` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_papers_academic_year` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_papers_uploaded_by` FOREIGN KEY (`uploaded_by`) REFERENCES `staff` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Note: Audit triggers can be added later if audit_logs table exists
-- ============================================================
