<?php /* Transport administration workspace; behaviour lives in transport_admin.js. */ ?>
<link rel="stylesheet" href="css/transport-admin.css?v=1">
<section class="transport-workspace" aria-labelledby="transportPageTitle">
 <div class="transport-hero"><div><div class="transport-eyebrow"><i class="bi bi-bus-front-fill"></i> OPERATIONS CONTROL</div><h1 id="transportPageTitle">Transport management</h1><p>Plan routes, manage vehicles and drivers, assign learners, monitor capacity, and reconcile transport collections.</p></div><div class="transport-hero-actions"><button class="btn btn-light" id="transportRefresh"><i class="bi bi-arrow-clockwise me-1"></i>Refresh</button><button class="btn btn-warning" id="transportAddRoute"><i class="bi bi-plus-lg me-1"></i>Add route</button></div></div>
 <div class="transport-kpis" id="transportKpis"><div class="transport-kpi"><span class="kpi-icon route"><i class="bi bi-signpost-2"></i></span><div><strong data-kpi="routes">—</strong><small>Active routes</small></div></div><div class="transport-kpi"><span class="kpi-icon vehicle"><i class="bi bi-bus-front"></i></span><div><strong data-kpi="vehicles">—</strong><small>Active vehicles</small></div></div><div class="transport-kpi"><span class="kpi-icon learner"><i class="bi bi-people"></i></span><div><strong data-kpi="learners">—</strong><small>Assigned learners</small></div></div><div class="transport-kpi"><span class="kpi-icon warning"><i class="bi bi-shield-exclamation"></i></span><div><strong data-kpi="attention">—</strong><small>Items needing attention</small></div></div></div>
 <div class="card border-success-subtle bg-light mb-3"><div class="card-body py-2"><div class="d-flex justify-content-between align-items-center gap-2"><div><strong><i class="bi bi-stars text-success me-1"></i>Transport operations assistant</strong><div class="small text-muted">Summarizes authorized capacity signals and suggests operational review questions. It does not assign routes or make safety decisions.</div></div><button type="button" class="btn btn-outline-success btn-sm" id="queueAiTransportSummary"><i class="bi bi-stars me-1"></i>Review operations</button></div><div id="aiTransportSummaries" class="row g-2 mt-2"></div></div></div>
 <div class="transport-toolbar"><div class="transport-tabs" role="tablist"><button class="transport-tab active" data-panel="routesPanel">Routes</button><button class="transport-tab" data-panel="vehiclesPanel">Vehicles</button><button class="transport-tab" data-panel="driversPanel">Drivers</button><button class="transport-tab" data-panel="stopsPanel">Stops</button><button class="transport-tab" data-panel="billingPanel">Collections</button></div><div class="transport-filters"><div class="input-group input-group-sm"><span class="input-group-text"><i class="bi bi-search"></i></span><input id="transportSearch" class="form-control" placeholder="Search transport"></div><select id="transportStatus" class="form-select form-select-sm"><option value="">All statuses</option><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="inactive">Inactive</option></select></div></div>
 <div class="transport-panel active" id="routesPanel"><div class="transport-panel-head"><div><h2>School transport routes</h2><p>Roads covered, ordered pickup/drop-off points, vehicles, drivers and daily times.</p></div><button class="btn btn-sm btn-outline-success" id="transportExport"><i class="bi bi-download me-1"></i>Export CSV</button></div><div class="table-responsive"><table class="table transport-table align-middle"><thead><tr><th>Route</th><th>Roads / areas covered</th><th>Morning / evening</th><th>Vehicle / driver</th><th>Stops</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody id="transportRoutesBody"><tr><td colspan="7" class="transport-loading">Loading routes…</td></tr></tbody></table></div></div>
 <div class="transport-panel" id="vehiclesPanel"><div class="transport-panel-head"><div><h2>Fleet register</h2><p>Capacity, insurance, service dates, and route assignment.</p></div><button class="btn btn-sm btn-success" id="transportAddVehicle"><i class="bi bi-plus-lg me-1"></i>Add vehicle</button></div><div class="table-responsive"><table class="table transport-table align-middle"><thead><tr><th>Registration</th><th>Type / model</th><th>Capacity</th><th>Insurance</th><th>Service due</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody id="transportVehiclesBody"></tbody></table></div></div>
 <div class="transport-panel" id="driversPanel"><div class="transport-panel-head"><div><h2>Driver register</h2><p>Active driver staff can be assigned to vehicles and routes.</p></div><button class="btn btn-sm btn-success" id="transportAddDriver"><i class="bi bi-person-plus me-1"></i>Add driver</button></div><div class="table-responsive"><table class="table transport-table align-middle"><thead><tr><th>Driver</th><th>Staff no.</th><th>Phone</th><th>Licence</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody id="transportDriversBody"></tbody></table></div></div>
 <div class="transport-panel" id="stopsPanel"><div class="transport-panel-head"><div><h2>Pickup and drop-off stops</h2><p>Stops remain ordered within their route and can be disabled safely.</p></div><button class="btn btn-sm btn-success" id="transportAddStop"><i class="bi bi-geo-alt me-1"></i>Add stop</button></div><div class="table-responsive"><table class="table transport-table align-middle"><thead><tr><th>Stop</th><th>Route</th><th>Sequence</th><th>Location</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody id="transportStopsBody"></tbody></table></div></div>
 <div class="transport-panel" id="billingPanel"><div class="transport-panel-head"><div><h2>Transport collections</h2><p>Verified payments allocated to transport entitlements.</p></div><div class="d-flex gap-2"><input type="month" id="transportBillingMonth" class="form-control form-control-sm"><button class="btn btn-sm btn-outline-success" id="transportLoadBilling">Load</button></div></div><div class="transport-collection-summary" id="transportBillingSummary"></div><div class="table-responsive"><table class="table transport-table align-middle"><thead><tr><th>Student</th><th>Route</th><th>Due</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody id="transportBillingBody"><tr><td colspan="6" class="transport-empty">Choose a month to view collections.</td></tr></tbody></table></div></div>
</section>
<div class="modal fade" id="transportEditorModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title" id="transportEditorTitle">Transport record</h5><small class="text-muted" id="transportEditorSubtitle"></small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body" id="transportEditorBody"></div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-success" id="transportEditorSave">Save changes</button></div></div></div></div>
<?php asset_script($appBase ?? '', 'js/pages/ai_transport_summary.js'); ?>
