(function () {
  const esc = (value) => { const el = document.createElement('div'); el.textContent = String(value ?? ''); return el.innerHTML; };
  const dates = () => ({ from: document.getElementById('fcFrom')?.value || new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10), to: document.getElementById('fcTo')?.value || new Date().toISOString().slice(0, 10) });
  const render = async () => {
    const host = document.getElementById('aiCateringReviews'); if (!host || !window.API?.catering) return;
    try {
      const own = await window.API.catering.getAiConsumptionReviews('own'); let review = { drafts: [] };
      try { review = await window.API.catering.getAiConsumptionReviews('review'); } catch (_) {}
      const rows = [...(own?.data?.drafts || own?.drafts || []).map((x) => ({ ...x, __review: false })), ...(review?.data?.drafts || review?.drafts || []).map((x) => ({ ...x, __review: true }))].filter((x) => x.metadata?.subject_type === 'catering_consumption_review');
      host.innerHTML = rows.length ? rows.map((draft) => { const body = draft.draft || {}; const approve = draft.__review && draft.status === 'pending_approval'; return `<div class="col-12"><article class="border rounded p-2"><div class="d-flex justify-content-between"><strong>${esc(body.title || 'Catering consumption review')}</strong><span class="badge text-bg-secondary">${esc(draft.status || 'queued')}</span></div><p class="small mt-2 mb-2">${esc(body.body || 'Review is still being generated.')}</p>${Array.isArray(body.next_steps) && body.next_steps.length ? `<ul class="small mb-2">${body.next_steps.map((step) => `<li>${esc(step)}</li>`).join('')}</ul>` : ''}${approve ? `<button class="btn btn-sm btn-success" data-ai-catering-approve="${Number(draft.id)}">Approve guidance</button>` : ''}${draft.status === 'approved' ? '<div class="small text-info">Approved for staff guidance. Catering records and controls remain authoritative.</div>' : ''}</article></div>`; }).join('') : '<div class="col-12 small text-muted">No catering variance review has been requested.</div>';
      host.querySelectorAll('[data-ai-catering-approve]').forEach((button) => button.addEventListener('click', async () => { try { await window.API.catering.approveAiConsumptionReview(button.dataset.aiCateringApprove); window.showNotification?.('Catering guidance approved', 'success'); await render(); } catch (error) { window.showNotification?.(error.message || 'Unable to approve catering guidance', 'danger'); } }));
    } catch (_) { host.innerHTML = '<div class="col-12 small text-warning">Catering assistance is temporarily unavailable.</div>'; }
  };
  const init = () => { document.getElementById('queueAiCateringReview')?.addEventListener('click', async () => { const button = document.getElementById('queueAiCateringReview'); const range = dates(); button.disabled = true; try { const result = await window.API.catering.queueAiConsumptionReview(range.from, range.to); window.showNotification?.(`Catering review queued${result?.job_id ? ` (job ${result.job_id})` : ''}`, 'info'); for (let i = 0; i < 6; i += 1) { await new Promise((resolve) => setTimeout(resolve, i === 0 ? 1000 : 2500)); await render(); } } catch (error) { window.showNotification?.(error.message || 'Unable to queue catering review', 'danger'); } finally { button.disabled = false; } }); render(); };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init, { once: true }); else init();
})();
