(() => {
  const $ = (id) => document.getElementById(id);
  const unwrap = (r) => r?.data?.data ?? r?.data ?? r;
  let currentBatch = null;
  function state(message, type='info'){ $('smState').className=`alert alert-${type}`; $('smState').textContent=message; }
  function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
  async function loadRefs(){ const d=unwrap(await API.staffMigration.referenceData()); $('smReference').innerHTML=`<b>Departments:</b> ${d.departments.map(x=>esc(`${x.code} — ${x.name}`)).join(', ')}<br><b>School roles:</b> ${d.roles.map(x=>esc(x.name)).join(', ')}`; }
  async function loadBatches(){ const rows=unwrap(await API.staffMigration.batches()) || []; $('smBatches').innerHTML=rows.length?rows.map(b=>`<tr><td>#${b.id}</td><td>${esc(b.source_filename)}</td><td>${b.valid_rows}/${b.total_rows}</td><td><span class="badge bg-secondary">${esc(b.status)}</span></td><td>${esc(b.imported_by_name)}</td><td>${esc(b.created_at)}</td><td><button class="btn btn-sm btn-outline-primary" data-view="${b.id}">View</button></td></tr>`).join(''):'<tr><td colspan="7" class="text-center text-muted py-4">No imports yet.</td></tr>'; }
  function render(detail){ currentBatch=detail.batch.id; $('smPreviewCard').classList.remove('d-none'); const b=detail.batch; $('smSummary').innerHTML=`<div class="col"><b>Total</b><div>${b.total_rows}</div></div><div class="col"><b>Valid</b><div>${b.valid_rows}</div></div><div class="col"><b>Invalid</b><div>${b.invalid_rows}</div></div><div class="col"><b>Status</b><div>${esc(b.status)}</div></div>`; $('smRows').innerHTML=detail.rows.map(r=>`<tr><td>${r.row_number}</td><td>${esc(`${r.data.first_name||''} ${r.data.last_name||''}`)}</td><td>${esc(r.data.email)}</td><td>${esc(r.data.department_code)}</td><td>${r.errors.length?`<button class="btn btn-sm btn-outline-danger" data-errors='${esc(JSON.stringify(r.errors))}'>${r.errors.length} errors</button>`:'<span class="badge bg-success">Valid</span>'}</td></tr>`).join(''); $('smCommit').disabled=!detail.can_commit; $('smRollback').disabled=!detail.can_rollback; }
  $('smTemplate')?.addEventListener('click',()=>location.href=API.staffMigration.templateUrl());
  $('smFile')?.addEventListener('change',()=>{$('smPreview').disabled=!$('smFile').files.length;});
  $('smPreview')?.addEventListener('click',async()=>{const f=$('smFile').files[0];if(!f)return;state('Uploading and validating…');const fd=new FormData();fd.append('file',f);try{render(unwrap(await API.staffMigration.stage(fd)));state('Validation completed.', 'success');await loadBatches();}catch(e){state(e.message||'Validation failed.','danger');}});
  $('smCommit')?.addEventListener('click',async()=>{if(!currentBatch||!confirm('Create all staff and user records from this validated batch?'))return;state('Importing atomically…');try{render(unwrap(await API.staffMigration.commit(currentBatch)).batch);state('Import completed and invitations queued.','success');await loadBatches();}catch(e){state(e.message||'Import failed. No partial records were kept.','danger');}});
  $('smRollback')?.addEventListener('click',async()=>{if(!currentBatch||!confirm('Rollback this import? This is blocked when operational records already exist.'))return;try{render(unwrap(await API.staffMigration.rollback(currentBatch)));state('Import rolled back.','success');await loadBatches();}catch(e){state(e.message||'Rollback blocked.','danger');}});
  $('smBatches')?.addEventListener('click',async e=>{const id=e.target.dataset.view;if(id)render(unwrap(await API.staffMigration.batch(id)));});
  $('smRows')?.addEventListener('click',e=>{if(e.target.dataset.errors)alert(JSON.parse(e.target.dataset.errors).join('\n'));});
  $('smRefresh')?.addEventListener('click',()=>Promise.all([loadRefs(),loadBatches()]));
  Promise.all([loadRefs(),loadBatches()]).then(()=>state('Ready. Download the template before preparing the migration file.','success')).catch(e=>state(e.message||'Workspace failed to load.','danger'));
})();
