const StaffLeaveController={
  requests:[],types:[],staff:[],
  async init(){await StaffAccess.init();if(!(StaffAccess.can('staff.leave.request')||StaffAccess.can('staff.leave.manage')||StaffAccess.can('staff.leave.approve'))){return StaffAccess.require('staff.leave.request');}this.bind();await Promise.all([this.loadTypes(),this.loadStaff(),this.loadRequests()]);StaffAccess.apply();},
  bind(){document.getElementById('newLeaveBtn')?.addEventListener('click',()=>bootstrap.Modal.getOrCreateInstance(document.getElementById('leaveRequestModal')).show());document.getElementById('submitLeaveBtn')?.addEventListener('click',()=>this.submit());document.getElementById('saveLeaveDecisionBtn')?.addEventListener('click',()=>this.saveDecision());document.getElementById('refreshLeaveBtn')?.addEventListener('click',()=>this.loadRequests());document.getElementById('leaveStatusFilter')?.addEventListener('change',()=>this.render());document.getElementById('leaveSearch')?.addEventListener('input',()=>this.render());},
  async loadTypes(){try{this.types=await API.staff.getLeaveTypes();document.getElementById('leaveTypeId').innerHTML='<option value="">Select leave type</option>'+this.types.map(t=>`<option value="${t.id}">${this.esc(t.name)}${t.days_allowed?` (${t.days_allowed} days)`:''}</option>`).join('');}catch(e){this.notify(e.message,'error');}},
  async loadStaff(){try{const r=await API.staff.list({limit:500});this.staff=Array.isArray(r)?r:(r?.items||[]);const opts=this.staff.map(s=>`<option value="${s.id}">${this.esc(s.staff_no||'')} — ${this.esc((s.first_name||'')+' '+(s.last_name||''))}</option>`).join('');document.getElementById('leaveStaffId').innerHTML='<option value="">Myself</option>'+opts;document.getElementById('leaveReliefId').innerHTML='<option value="">None</option>'+opts;}catch(e){if(StaffAccess.can('staff.leave.manage'))this.notify(e.message,'error');}},
  async loadRequests(){const body=document.getElementById('leaveBody');body.innerHTML='<tr><td colspan="7" class="text-center py-4"><span class="spinner-border spinner-border-sm"></span></td></tr>';try{const r=await API.staff.getLeaveRequests();this.requests=Array.isArray(r)?r:(r?.items||r?.data||[]);this.render();}catch(e){body.innerHTML=`<tr><td colspan="7" class="text-danger text-center py-4">${this.esc(e.message)}</td></tr>`;}},
  render(){const q=(document.getElementById('leaveSearch')?.value||'').toLowerCase(),st=document.getElementById('leaveStatusFilter')?.value||'';const rows=this.requests.filter(x=>(!st||x.status===st)&&(!q||`${x.staff_name||''} ${x.first_name||''} ${x.last_name||''} ${x.leave_type_name||x.leave_type||''}`.toLowerCase().includes(q)));document.getElementById('leavePending').textContent=this.requests.filter(x=>x.status==='pending').length;document.getElementById('leaveApproved').textContent=this.requests.filter(x=>x.status==='approved').length;document.getElementById('leaveRejected').textContent=this.requests.filter(x=>x.status==='rejected').length;document.getElementById('leaveDaysTotal').textContent=this.requests.reduce((n,x)=>n+Number(x.days_requested||0),0);document.getElementById('leaveBody').innerHTML=rows.length?rows.map(x=>`<tr><td><strong>${this.esc(x.staff_name||`${x.first_name||''} ${x.last_name||''}`)}</strong><br><small>${this.esc(x.staff_no||'')}</small></td><td>${this.esc(x.leave_type_name||x.leave_type||'—')}</td><td>${this.esc(x.start_date)} → ${this.esc(x.end_date)}</td><td>${this.esc(x.days_requested)}</td><td>${this.esc(x.reason)}</td><td><span class="badge bg-${x.status==='approved'?'success':x.status==='rejected'?'danger':x.status==='pending'?'warning':'secondary'}">${this.esc(x.status)}</span></td><td class="text-end">${x.status==='pending'&&StaffAccess.can('staff.leave.approve')?`<button class="btn btn-sm btn-outline-primary" onclick="StaffLeaveController.openDecision(${x.id})">Decide</button>`:''}</td></tr>`).join(''):'<tr><td colspan="7" class="text-center text-muted py-4">No leave requests found.</td></tr>';},
  async submit(){const start=document.getElementById('leaveStart').value,end=document.getElementById('leaveEnd').value;if(!start||!end||!document.getElementById('leaveTypeId').value||!document.getElementById('leaveReason').value.trim())return this.notify('Complete all required fields','error');if(new Date(end)<new Date(start))return this.notify('End date cannot be before start date','error');const days=Math.floor((new Date(end)-new Date(start))/86400000)+1;const payload={staff_id:document.getElementById('leaveStaffId').value||undefined,leave_type_id:Number(document.getElementById('leaveTypeId').value),start_date:start,end_date:end,days_requested:days,reason:document.getElementById('leaveReason').value.trim(),relief_staff_id:document.getElementById('leaveReliefId').value||null};try{await API.staff.createLeaveRequest(payload);bootstrap.Modal.getInstance(document.getElementById('leaveRequestModal'))?.hide();await this.loadRequests();this.notify('Leave request submitted','success');}catch(e){this.notify(e.message,'error');}},
  openDecision(id){document.getElementById('decisionLeaveId').value=id;document.getElementById('leaveDecisionReason').value='';bootstrap.Modal.getOrCreateInstance(document.getElementById('leaveDecisionModal')).show();},
  async saveDecision(){const id=Number(document.getElementById('decisionLeaveId').value),status=document.getElementById('leaveDecision').value,reason=document.getElementById('leaveDecisionReason').value.trim();if(status==='rejected'&&!reason)return this.notify('A rejection reason is required','error');try{await API.staff.updateLeaveRequestStatus(id,{status,rejection_reason:reason,reason});bootstrap.Modal.getInstance(document.getElementById('leaveDecisionModal'))?.hide();await this.loadRequests();this.notify('Leave decision saved','success');}catch(e){this.notify(e.message,'error');}},
  notify(m,t='info'){window.API?.showNotification?.(m,t)||alert(m);},esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML;}
};document.addEventListener('DOMContentLoaded',()=>StaffLeaveController.init());
