(function(){
 const state={data:null,refs:null}; const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 function alertMsg(m,t='danger'){ $('#lifecycleAlert').innerHTML=`<div class="alert alert-${t}">${esc(m)}</div>`; }
 async function load(){ try{ $('#staffLifecycleRows').innerHTML='<tr><td colspan="6" class="text-center py-5"><span class="spinner-border"></span></td></tr>'; const [data,refs]=await Promise.all([API.staffLifecycle.list({status:$('#staffStatus').value}),API.staffLifecycle.referenceData()]); state.data=data;state.refs=refs;render();fillForm(); }catch(e){alertMsg(e.message||'Unable to load staff lifecycle');} }
 function render(){ const s=state.data.summary||{}; $('#lifecycleSummary').innerHTML=[['Total',s.total],['Active',s.active],['Suspended',s.suspended],['Pending actions',s.pending_actions]].map(x=>`<div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-muted small">${x[0]}</div><div class="fs-3 fw-bold">${Number(x[1]||0)}</div></div></div></div>`).join(''); const q=$('#staffSearch').value.toLowerCase(); const rows=(state.data.staff||[]).filter(r=>[r.staff_no,r.first_name,r.last_name,r.position,r.department_name].join(' ').toLowerCase().includes(q)); $('#staffLifecycleRows').innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.first_name)} ${esc(r.last_name)}</strong><div class="small text-muted">${esc(r.staff_no)} · ${esc(r.email)}</div></td><td>${esc(r.position)}</td><td>${esc(r.department_name||'—')}</td><td><span class="badge bg-${r.status==='active'?'success':r.status==='suspended'?'warning':'secondary'}">${esc(r.status)}</span></td><td>${esc(r.onboarding_status)}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-timeline="${r.id}">View timeline</button></td></tr>`).join(''); $('#staffLifecycleEmpty').classList.toggle('d-none',rows.length>0); }
 function fillForm(){ const f=$('#lifecycleActionForm'); f.staff_id.innerHTML='<option value="">Select staff</option>'+state.refs.staff.map(x=>`<option value="${x.id}">${esc(x.staff_no)} — ${esc(x.name)}</option>`).join(''); f.action_type.innerHTML='<option value="">Select action</option>'+state.refs.action_types.map(x=>`<option value="${x}">${esc(x.replaceAll('_',' '))}</option>`).join(''); f.to_department_id.innerHTML='<option value="">Keep current</option>'+state.refs.departments.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join(''); }
 async function timeline(id){ try{ const d=await API.staffLifecycle.get(id); $('#staffTimelineBody').innerHTML=`<h5>${esc(d.staff.first_name)} ${esc(d.staff.last_name)}</h5><p class="text-muted">${esc(d.staff.staff_no)} · ${esc(d.staff.position)} · ${esc(d.staff.department_name||'')}</p>`+(d.timeline.length?`<div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Action</th><th>Change</th><th>Status</th><th>Approval</th></tr></thead><tbody>${d.timeline.map(a=>`<tr><td>${esc(a.effective_date)}</td><td>${esc(a.action_type.replaceAll('_',' '))}</td><td>${esc(a.from_position||'—')} → ${esc(a.to_position||'—')}</td><td>${esc(a.status)}</td><td>${esc(a.approved_by_name||'Pending')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="alert alert-info">No lifecycle actions recorded.</div>'); bootstrap.Modal.getOrCreateInstance($('#staffTimelineModal')).show(); }catch(e){alertMsg(e.message);} }
 document.addEventListener('DOMContentLoaded',()=>{ $('#newLifecycleAction').onclick=()=>bootstrap.Modal.getOrCreateInstance($('#lifecycleActionModal')).show(); $('#refreshLifecycle').onclick=load; $('#staffStatus').onchange=load; $('#staffSearch').oninput=render; $('#staffLifecycleRows').onclick=e=>{const b=e.target.closest('[data-timeline]');if(b)timeline(b.dataset.timeline)}; $('#lifecycleActionForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target)); try{await API.staffLifecycle.createAction(data);bootstrap.Modal.getInstance($('#lifecycleActionModal')).hide();e.target.reset();alertMsg('Action submitted for approval.','success');load();}catch(err){alertMsg(err.message)}}; load(); });
})();
