(function(){'use strict';
const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML;};
const parentToken=(()=>{try{return sessionStorage.getItem('pp_token');}catch(_){return null;}})();
const token=parentToken;
const state={products:[],cart:null,children:[],mode:parentToken?'parent':'guest'};
const api=(path,method='GET',body)=>state.mode==='parent'?apiCall('/parent-portal'+path,method,body,null,{noRedirect:true}):apiCall('/public/uniform-catalog',method,body,null,{noRedirect:true});
function showError(message){const el=document.getElementById('catalogError');el.textContent=message;el.classList.remove('d-none');}
function render(){const q=(document.getElementById('catalogSearch').value||'').toLowerCase();const rows=state.products.filter(p=>!q||(`${p.title} ${p.description||''}`).toLowerCase().includes(q));document.getElementById('catalogCount').textContent=`${rows.length} item${rows.length===1?'':'s'}`;document.getElementById('catalogGrid').innerHTML=rows.map(p=>{const sizes=p.sizes||[];const image=p.image_url||`${window.APP_BASE||''}/images/official_school_logo.png`;return `<div class="col-sm-6 col-xl-4"><article class="card product-card h-100"><img class="product-img w-100" src="${esc(image)}" onerror="this.src='${window.APP_BASE||''}/images/official_school_logo.png'" alt="${esc(p.title)}"><div class="product-body d-flex flex-column h-100"><div class="d-flex justify-content-between gap-2"><h5 class="fw-bold mb-2">${esc(p.title)}</h5><span class="badge store-badge align-self-start">${sizes.length?'Available':'Out of stock'}</span></div><p class="text-muted small flex-grow-1">${esc(p.description||'Official Kingsway school-store item.')}</p>${sizes.length?`<label class="small fw-semibold mb-1">Choose size</label><select class="form-select size-select mb-2" data-size="${p.id}">${sizes.map(s=>`<option value="${s.size_id}">${esc(s.size_label||s.size)} · KES ${Number(s.unit_price).toLocaleString()}</option>`).join('')}</select><div class="d-flex gap-2"><input class="form-control qty-input" data-qty="${p.id}" type="number" min="1" value="1" style="max-width:82px"><button class="btn btn-success flex-grow-1 rounded-pill" data-add="${p.id}">${token?'<i class="bi bi-bag-plus me-1"></i>Add to cart':'Sign in to buy'}</button></div>`:'<div class="alert alert-light small mb-0">Please check back soon.</div>'}</div></article></div>`;}).join('')||'<div class="col-12"><div class="empty-state text-center p-5"><i class="bi bi-search fs-1 text-success"></i><h5 class="mt-3">No uniforms found</h5><p class="text-muted mb-0">Try another search.</p></div></div>';document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.add)));}
async function addToCart(productId){const sizeId=Number(document.querySelector(`[data-size="${productId}"]`).value);const quantity=Number(document.querySelector(`[data-qty="${productId}"]`).value);if(!token){location.href=(window.APP_BASE||'')+'/parent_portal.php';return;}try{state.cart=(await api('/uniform-cart','POST',{product_id:Number(productId),size_id:sizeId,quantity})).data||state.cart;updateCartButton();toast('Added to your cart');}catch(e){showError(e.message||'Unable to add this item.');}}
function updateCartButton(){if(!token)return;const count=(state.cart?.items||[]).reduce((n,x)=>n+Number(x.quantity||0),0);document.getElementById('cartButton').classList.toggle('d-none',count<1);document.getElementById('cartCount').textContent=count;}
function renderCart(){const items=state.cart?.items||[];document.getElementById('cartBody').innerHTML=items.length?items.map(x=>`<div class="cart-item py-3 d-flex justify-content-between gap-3"><div><div class="fw-semibold">${esc(x.title)}</div><small class="text-muted">${esc(x.size_label||x.size)} × ${x.quantity}</small></div><strong>KES ${Number(x.line_total).toLocaleString()}</strong></div>`).join(''):'<div class="text-center text-muted py-5"><i class="bi bi-bag fs-1"></i><p class="mt-2">Your cart is empty.</p></div>';document.getElementById('cartTotal').textContent=`KES ${Number(state.cart?.total||0).toLocaleString()}`;document.getElementById('checkoutButton').disabled=!items.length;}
async function openCheckout(){if(!state.children.length){try{const r=await api('/dashboard');const d=r.data||r;state.children=d.children||d.students||[];}catch(e){showError('Please sign in to the parent portal before paying.');return;}}document.getElementById('checkoutStudent').innerHTML=state.children.map(c=>`<option value="${c.id||c.student_id}">${esc(c.name||c.student_name||c.admission_no||'Learner')}</option>`).join('');document.getElementById('checkoutAmount').value=Number(state.cart?.total||0).toFixed(2);bootstrap.Modal.getOrCreateInstance(document.getElementById('checkoutModal')).show();}
async function submitCheckout(){const err=document.getElementById('checkoutError');err.classList.add('d-none');const button=document.getElementById('checkoutSubmit');button.disabled=true;try{const data={student_id:Number(document.getElementById('checkoutStudent').value),amount:Number(document.getElementById('checkoutAmount').value),channel:'daraja_mpesa',phone:document.getElementById('checkoutPhone').value};const r=await api('/uniform-checkout-payment','POST',data);bootstrap.Modal.getInstance(document.getElementById('checkoutModal')).hide();toast('STK prompt sent. Enter your M-Pesa PIN on your phone.');}catch(e){err.textContent=e.message||'Unable to start payment.';err.classList.remove('d-none');}finally{button.disabled=false;}}
function toast(message){if(window.showNotification)showNotification(message,'success');else alert(message);}
async function load(){try{const r=await api(state.mode==='parent'?'/uniform-catalog':'');const d=r.data||r;state.products=d.products||[];render();if(state.mode==='parent'){state.cart=(await api('/uniform-cart')).data||null;updateCartButton();}}catch(e){showError(e.message||'Unable to load the catalogue.');}}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('catalogSearch').addEventListener('input',render);document.getElementById('cartButton').addEventListener('click',()=>{renderCart();bootstrap.Modal.getOrCreateInstance(document.getElementById('cartModal')).show();});document.getElementById('checkoutButton').addEventListener('click',openCheckout);document.getElementById('checkoutSubmit').addEventListener('click',submitCheckout);load();});
})();
