<?php
declare(strict_types=1);

namespace App\API\Services\catalog;

use App\API\Services\ReadReplicaService;
use App\API\Services\FinancialPostingCoordinator;
use App\API\Services\Logger;
use App\API\Services\UploadService;
use App\API\Services\payments\FinancialAccountService;
use App\API\Services\payments\KcbMpesaExpressService;
use App\API\Services\payments\MpesaPaymentService;
use App\API\Services\payments\ReferenceNormalizer;
use PDO;
use RuntimeException;

/** Stock-safe commerce shared by parent and authenticated staff catalogues. */
final class CatalogCommerceService
{
    private UploadService $uploads;

    public function __construct(private PDO $db) { $this->uploads = new UploadService(); }

    private function buyer(string $type, int $id): void
    {
        if (!in_array($type, ['parent','staff'], true) || $id < 1) throw new RuntimeException('A valid catalogue buyer is required');
    }

    private function visibility(string $type): string
    {
        return $type === 'parent' ? "p.status='active' AND p.published=1" : "p.status='active'";
    }

    private function publicImageUrl(?string $stored): ?string
    {
        return $this->uploads->publicUrl($stored);
    }

    public function product(int $id, string $buyerType): array
    {
        $sql = "SELECT p.*,i.code,COALESCE((SELECT im.url FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_images") . " im WHERE im.product_id=p.id AND im.variant_id IS NULL ORDER BY im.is_primary DESC,im.display_order,im.id LIMIT 1),(SELECT im.url FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_images") . " im JOIN uniform_catalog_variants v ON v.id=im.variant_id WHERE v.product_id=p.id AND v.status='active' ORDER BY v.is_default DESC,v.display_order,im.is_primary DESC,im.id LIMIT 1)) image_url FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_products") . " p JOIN " . ReadReplicaService::qualifiedRef("inventory_items") . " i ON i.id=p.item_id WHERE p.id=? AND ".$this->visibility($buyerType);
        $s=$this->db->prepare($sql);$s->execute([$id]);$p=$s->fetch(PDO::FETCH_ASSOC);if(!$p)throw new RuntimeException('Product not found');
        $v=$this->db->prepare("SELECT v.*,(SELECT im.url FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_images") . " im WHERE im.variant_id=v.id ORDER BY im.is_primary DESC,im.display_order,im.id LIMIT 1) image_url FROM uniform_catalog_variants v WHERE v.product_id=? AND v.status='active' ORDER BY v.is_default DESC,v.display_order,v.id");$v->execute([$id]);$variants=$v->fetchAll(PDO::FETCH_ASSOC);foreach($variants as &$vv){$vv['image_url']=$this->publicImageUrl($vv['image_url']??null);}$p['variants']=$variants;
        $im=$this->db->prepare('SELECT id,variant_id,url,alt_text,view_type,is_primary,display_order FROM uniform_catalog_images WHERE product_id=? ORDER BY variant_id,is_primary DESC,display_order,id');$im->execute([$id]);$images=$im->fetchAll(PDO::FETCH_ASSOC);foreach($images as &$img){$img['url']=$this->publicImageUrl($img['url']??null);}$p['images']=$images;
        $sz=$this->db->prepare("SELECT us.id size_id,NULL variant_id,us.size,us.size_label,us.size_type,us.unit_price,GREATEST(0,us.quantity_available-us.quantity_reserved) available FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_products") . " JOIN " . ReadReplicaService::qualifiedRef("uniform_sizes") . " us ON us.item_id=p.item_id WHERE p.id=? UNION ALL SELECT us.id,v.id,us.size,us.size_label,us.size_type,us.unit_price,GREATEST(0,us.quantity_available-us.quantity_reserved) FROM uniform_catalog_variants v JOIN " . ReadReplicaService::qualifiedRef("uniform_sizes") . " us ON us.item_id=v.item_id WHERE v.product_id=? AND v.status='active' ORDER BY variant_id,size");$sz->execute([$id,$id]);$p['sizes']=$sz->fetchAll(PDO::FETCH_ASSOC);
        $p['reviews']=$this->reviews($id);$p['image_url']=$this->publicImageUrl($p['image_url']??null);return $p;
    }

    private function openCart(string $type,int $buyerId,bool $create=true): int
    {
        $s=$this->db->prepare("SELECT id FROM catalog_carts WHERE buyer_type=? AND buyer_id=? AND status='open' ORDER BY id DESC LIMIT 1");$s->execute([$type,$buyerId]);$id=(int)$s->fetchColumn();
        if(!$id&&$create){$this->db->prepare('INSERT INTO catalog_carts(buyer_type,buyer_id) VALUES(?,?)')->execute([$type,$buyerId]);$id=(int)$this->db->lastInsertId();}return $id;
    }

    public function cart(string $type,int $buyerId): array
    {
        $this->buyer($type,$buyerId);$id=$this->openCart($type,$buyerId,false);if(!$id)return ['cart_id'=>null,'items'=>[],'total'=>0.0,'count'=>0];
        $s=$this->db->prepare("SELECT ci.id,ci.product_id,ci.variant_id,ci.size_id,ci.quantity,p.title,p.slug,p.published,v.name variant_name,v.color_name,us.size,us.size_label,us.unit_price,GREATEST(0,us.quantity_available-us.quantity_reserved) available,(ci.quantity*us.unit_price) line_total,COALESCE((SELECT im.url FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_images") . " im WHERE im.variant_id=ci.variant_id ORDER BY im.is_primary DESC,im.display_order,im.id LIMIT 1),(SELECT im.url FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_images") . " im WHERE im.product_id=p.id AND im.variant_id IS NULL ORDER BY im.is_primary DESC,im.display_order,im.id LIMIT 1)) image_url FROM catalog_cart_items ci JOIN " . ReadReplicaService::qualifiedRef("uniform_catalog_products") . " p ON p.id=ci.product_id LEFT JOIN uniform_catalog_variants v ON v.id=ci.variant_id JOIN " . ReadReplicaService::qualifiedRef("uniform_sizes") . " us ON us.id=ci.size_id WHERE ci.cart_id=? ORDER BY ci.id");$s->execute([$id]);$items=$s->fetchAll(PDO::FETCH_ASSOC);foreach($items as &$it){$it['image_url']=$this->publicImageUrl($it['image_url']??null);}unset($it);$total=0.0;$count=0;foreach($items as $x){$total+=(float)$x['line_total'];$count+=(int)$x['quantity'];}return ['cart_id'=>$id,'items'=>$items,'total'=>$total,'count'=>$count];
    }

    public function paymentOptions(bool $includeManual=false): array
    {
        $service=new FinancialAccountService($this->db);$map=['daraja_mpesa'=>'mpesa_stk','buni_mpesa'=>'buni_ipn'];if($includeManual)$map+=['cash'=>'cash','bank_transfer'=>'bank_transfer','cheque'=>'cheque'];$result=[];foreach($map as $channel=>$code){$accounts=$service->listAvailable('uniforms',$code);if($accounts)$result[]=['channel'=>$channel,'label'=>['daraja_mpesa'=>'M-Pesa STK Push','buni_mpesa'=>'KCB Buni M-Pesa','cash'=>'Cash','bank_transfer'=>'Bank transfer','cheque'=>'Cheque'][$channel],'accounts'=>$accounts];}return $result;
    }

    private function purchasableLine(int $productId,?int $variantId,int $sizeId,string $type,bool $lock=false): array
    {
        $lockSql=$lock?' FOR UPDATE':'';$sql="SELECT p.id product_id,p.item_id base_item_id,p.title,p.published,v.id variant_id,v.name variant_name,COALESCE(v.item_id,p.item_id) item_id,us.id size_id,us.size,us.size_label,us.unit_price,us.quantity_available,us.quantity_reserved FROM uniform_catalog_products p LEFT JOIN uniform_catalog_variants v ON v.id=? AND v.product_id=p.id AND v.status='active' JOIN uniform_sizes us ON us.id=? AND us.item_id=COALESCE(v.item_id,p.item_id) WHERE p.id=? AND ".$this->visibility($type).$lockSql;
        $s=$this->db->prepare($sql);$s->execute([$variantId,$sizeId,$productId]);$row=$s->fetch(PDO::FETCH_ASSOC);if(!$row)throw new RuntimeException('The selected product variant or size is unavailable');return $row;
    }

    public function addCart(string $type,int $buyerId,array $data): array
    {
        $this->buyer($type,$buyerId);$product=(int)($data['product_id']??0);$variant=(int)($data['variant_id']??0)?:null;$size=(int)($data['size_id']??0);$qty=(int)($data['quantity']??1);if($qty<1||$qty>20)throw new RuntimeException('Quantity must be between 1 and 20');$line=$this->purchasableLine($product,$variant,$size,$type);if((int)$line['quantity_available']-(int)$line['quantity_reserved']<$qty)throw new RuntimeException('Requested quantity is not in stock');$cart=$this->openCart($type,$buyerId);
        $find=$this->db->prepare('SELECT id,quantity FROM catalog_cart_items WHERE cart_id=? AND product_id=? AND size_id=? AND variant_id <=> ?');$find->execute([$cart,$product,$size,$variant]);$existing=$find->fetch(PDO::FETCH_ASSOC);$newQty=$qty+(int)($existing['quantity']??0);if($newQty>(int)$line['quantity_available']-(int)$line['quantity_reserved'])throw new RuntimeException('Cart quantity exceeds available stock');if($existing)$this->db->prepare('UPDATE catalog_cart_items SET quantity=? WHERE id=?')->execute([$newQty,$existing['id']]);else $this->db->prepare('INSERT INTO catalog_cart_items(cart_id,product_id,variant_id,size_id,quantity) VALUES(?,?,?,?,?)')->execute([$cart,$product,$variant,$size,$qty]);$this->db->prepare('DELETE FROM catalog_wishlists WHERE buyer_type=? AND buyer_id=? AND product_id=?')->execute([$type,$buyerId,$product]);return $this->cart($type,$buyerId);
    }

    public function updateCart(string $type,int $buyerId,int $lineId,int $qty): array
    {
        $this->buyer($type,$buyerId);$cart=$this->openCart($type,$buyerId,false);if(!$cart)throw new RuntimeException('Cart not found');if($qty<=0){$this->db->prepare('DELETE FROM catalog_cart_items WHERE id=? AND cart_id=?')->execute([$lineId,$cart]);return $this->cart($type,$buyerId);} $s=$this->db->prepare('SELECT * FROM catalog_cart_items WHERE id=? AND cart_id=?');$s->execute([$lineId,$cart]);$item=$s->fetch(PDO::FETCH_ASSOC);if(!$item)throw new RuntimeException('Cart item not found');$line=$this->purchasableLine((int)$item['product_id'],(int)$item['variant_id']?:null,(int)$item['size_id'],$type);if($qty>(int)$line['quantity_available']-(int)$line['quantity_reserved'])throw new RuntimeException('Cart quantity exceeds available stock');$this->db->prepare('UPDATE catalog_cart_items SET quantity=? WHERE id=?')->execute([$qty,$lineId]);return $this->cart($type,$buyerId);
    }

    public function removeCart(string $type,int $buyerId,int $lineId): array { return $this->updateCart($type,$buyerId,$lineId,0); }

    public function wishlist(string $type,int $buyerId): array
    {
        $this->buyer($type,$buyerId);$s=$this->db->prepare("SELECT w.id,w.product_id,w.created_at,p.title,p.description,p.category_slug,p.published,(SELECT im.url FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_images") . " WHERE im.product_id=p.id ORDER BY im.is_primary DESC,im.display_order,im.id LIMIT 1) image_url FROM " . ReadReplicaService::qualifiedRef("catalog_wishlists") . " w JOIN " . ReadReplicaService::qualifiedRef("uniform_catalog_products") . " p ON p.id=w.product_id WHERE w.buyer_type=? AND w.buyer_id=? AND ".$this->visibility($type)." ORDER BY w.created_at DESC");$s->execute([$type,$buyerId]);$rows=$s->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$r)$r['image_url']=$this->publicImageUrl($r['image_url']??null);unset($r);return $rows;
    }
    public function addWishlist(string $type,int $buyerId,int $productId): array { $this->buyer($type,$buyerId);$this->product($productId,$type);$this->db->prepare('INSERT INTO catalog_wishlists(buyer_type,buyer_id,product_id) VALUES(?,?,?) ON DUPLICATE KEY UPDATE created_at=created_at')->execute([$type,$buyerId,$productId]);return $this->wishlist($type,$buyerId); }
    public function removeWishlist(string $type,int $buyerId,int $productId): array { $this->buyer($type,$buyerId);$this->db->prepare('DELETE FROM catalog_wishlists WHERE buyer_type=? AND buyer_id=? AND product_id=?')->execute([$type,$buyerId,$productId]);return $this->wishlist($type,$buyerId); }

    public function checkout(string $type,int $buyerId,array $data,int $actorUserId=0): array
    {
        $this->buyer($type,$buyerId);$studentId=(int)($data['student_id']??0)?:null;if($type==='parent'&&!$studentId)throw new RuntimeException('Select the learner receiving this order');if($type==='parent'){$v=$this->db->prepare('SELECT 1 FROM student_parents WHERE parent_id=? AND student_id=? LIMIT 1');$v->execute([$buyerId,$studentId]);if(!$v->fetchColumn())throw new RuntimeException('The selected learner is not connected to this parent');}
        $channel=(string)($data['channel']??'daraja_mpesa');if(!in_array($channel,['daraja_mpesa','buni_mpesa','cash','bank_transfer','cheque'],true))throw new RuntimeException('Unsupported payment channel');if(in_array($channel,['cash','bank_transfer','cheque'],true)&&empty($data['allow_manual']))throw new RuntimeException('Manual payments must be recorded at the Uniform Store');
        $this->db->beginTransaction();try{$cartId=$this->openCart($type,$buyerId,false);if(!$cartId)throw new RuntimeException('Your cart is empty');$items=$this->db->prepare('SELECT * FROM catalog_cart_items WHERE cart_id=? ORDER BY id FOR UPDATE');$items->execute([$cartId]);$cartItems=$items->fetchAll(PDO::FETCH_ASSOC);if(!$cartItems)throw new RuntimeException('Your cart is empty');$lines=[];$subtotal=0.0;foreach($cartItems as $item){$line=$this->purchasableLine((int)$item['product_id'],(int)$item['variant_id']?:null,(int)$item['size_id'],$type,true);$qty=(int)$item['quantity'];if((int)$line['quantity_available']-(int)$line['quantity_reserved']<$qty)throw new RuntimeException($line['title'].' no longer has enough stock');$line['quantity']=$qty;$line['line_total']=$qty*(float)$line['unit_price'];$subtotal+=(float)$line['line_total'];$lines[]=$line;}
            $source=$type==='parent'?'online':'internal';$discountChannel=$type==='parent'?'public':'internal';$stock=new CatalogStockService($this->db);$quote=$stock->quoteDiscount($data['discount_code']??null,$discountChannel,$subtotal,$lines,$type,$buyerId);$discount=(float)($quote['amount']??0);$total=max(0,$subtotal-$discount);
            $ref='KPS-'.strtoupper($type[0]).'-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(4)));$this->db->prepare("INSERT INTO catalog_orders(order_reference,buyer_type,buyer_id,student_id,source,status,payment_status,subtotal,discount_total,total_amount,customer_note,placed_by) VALUES(?,?,?,?,?,'pending_payment','pending',?,?,?,?,?)")->execute([$ref,$type,$buyerId,$studentId,$source,$subtotal,$discount,$total,$data['note']??null,$actorUserId?:null]);$orderId=(int)$this->db->lastInsertId();$insert=$this->db->prepare('INSERT INTO catalog_order_items(order_id,product_id,variant_id,size_id,item_id,product_title,variant_name,size_label,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$reserve=$this->db->prepare('UPDATE uniform_sizes SET quantity_reserved=quantity_reserved+? WHERE id=?');foreach($lines as $line){$insert->execute([$orderId,$line['product_id'],$line['variant_id']?:null,$line['size_id'],$line['item_id'],$line['title'],$line['variant_name'],$line['size_label']?:$line['size'],$line['quantity'],$line['unit_price'],$line['line_total']]);$reserve->execute([$line['quantity'],$line['size_id']]);}if($quote)$stock->recordDiscount($orderId,$quote,$type,$buyerId,$actorUserId);$this->db->prepare("UPDATE catalog_carts SET status='converted' WHERE id=?")->execute([$cartId]);$this->event($orderId,'order_placed',null,'pending_payment',$data['note']??null,$actorUserId);$this->db->commit();
            Logger::audit('catalog_order_placed','catalog_order',$orderId,'Catalogue order placed',['buyer_type'=>$type,'buyer_id'=>$buyerId,'order_reference'=>$ref,'subtotal'=>$subtotal,'discount'=>$discount,'amount'=>$total,'channel'=>$channel]);return $this->startPayment($orderId,$channel,$data,$actorUserId);
        }catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }

    private function startPayment(int $orderId,string $channel,array $data,int $actor): array
    {
        $order=$this->order($orderId);$channelCode=['daraja_mpesa'=>'mpesa_stk','buni_mpesa'=>'buni_ipn','cash'=>'cash','bank_transfer'=>'bank_transfer','cheque'=>'cheque'][$channel];$account=(new FinancialAccountService($this->db))->requireFor((int)($data['financial_account_id']??0),'uniforms',$channelCode);$attemptCount=$this->db->prepare('SELECT COUNT(*) FROM catalog_payment_attempts WHERE order_id=?');$attemptCount->execute([$orderId]);$number=(int)$attemptCount->fetchColumn()+1;$ref=$order['order_reference'].($number>1?'-R'.$number:'');$status=in_array($channel,['cash','bank_transfer','cheque'],true)?'manual_review':'pending';$this->db->prepare('INSERT INTO catalog_payment_attempts(order_id,channel,amount,status,idempotency_reference,financial_account_id,request_json,created_by) VALUES(?,?,?,?,?,?,?,?)')->execute([$orderId,$channel,$order['total_amount'],$status,$ref,$account['id'],json_encode($data),$actor?:null]);$attempt=(int)$this->db->lastInsertId();$provider=[];
        if (!empty($order['student_id'])) {
            $normalized=(new ReferenceNormalizer())->reference($ref);
            $this->db->prepare("INSERT IGNORE INTO payment_routing_references(reference,normalized_reference,purpose,student_id,expires_at) VALUES(?,?, 'uniforms',?,DATE_ADD(NOW(),INTERVAL 30 DAY))")->execute([$ref,$normalized,(int)$order['student_id']]);
        }
        try {
            if($channel==='daraja_mpesa'){$provider=(new MpesaPaymentService())->initiateSTKPush($ref,(string)($data['phone']??''),(float)$order['total_amount'],'Kingsway catalogue order',(int)$account['id']);$request=$provider['data']['checkout_request_id']??$provider['checkout_request_id']??null;$ok=($provider['accepted']??false)||(($provider['status']??'')==='pending');$this->db->prepare('UPDATE catalog_payment_attempts SET status=?,provider_request_id=?,response_json=? WHERE id=?')->execute([$ok?'accepted':'failed',$request,json_encode($provider),$attempt]);$this->db->prepare("UPDATE catalog_orders SET status=? WHERE id=?")->execute([$ok?'payment_processing':'pending_payment',$orderId]);}
            elseif($channel==='buni_mpesa'){$base=defined('KCB_CALLBACK_BASE_URL')?KCB_CALLBACK_BASE_URL:(defined('BASE_URL')?BASE_URL:'');$provider=(new KcbMpesaExpressService())->initiate(['phone_number'=>$data['phone']??'','amount'=>$order['total_amount'],'invoice_number'=>$ref,'org_short_code'=>(string)$account['account_identifier'],'description'=>'Kingsway catalogue order','callback_url'=>rtrim($base,'/').'/api/payments/kcb-mpesa-express-callback']);$request=$provider['checkout_request_id']??$provider['message_id']??null;$this->db->prepare("UPDATE catalog_payment_attempts SET status='accepted',provider_request_id=?,response_json=? WHERE id=?")->execute([$request,json_encode($provider),$attempt]);$this->db->prepare("UPDATE catalog_orders SET status='payment_processing' WHERE id=?")->execute([$orderId]);}
        } catch (\Throwable $e) {
            $provider=['accepted'=>false,'message'=>'Payment request could not be started. Retry from your order history.'];$this->db->prepare("UPDATE catalog_payment_attempts SET status='failed',response_json=? WHERE id=?")->execute([json_encode(['error'=>$e->getMessage()]),$attempt]);$this->db->prepare("UPDATE catalog_orders SET status='pending_payment' WHERE id=?")->execute([$orderId]);
        }
        return ['order'=>$this->order($orderId),'payment_attempt_id'=>$attempt,'provider'=>$provider,'checkout_request_id'=>$request??null];
    }

    public function retryPayment(int $orderId,string $type,int $buyerId,array $data,int $actor=0): array
    {
        $this->buyer($type,$buyerId);$order=$this->order($orderId);if($order['buyer_type']!==$type||(int)$order['buyer_id']!==$buyerId)throw new RuntimeException('Order not found');if(!in_array($order['status'],['pending_payment','payment_processing'],true)||$order['payment_status']==='paid')throw new RuntimeException('This order is not awaiting payment');$channel=(string)($data['channel']??'daraja_mpesa');if(!in_array($channel,['daraja_mpesa','buni_mpesa'],true))throw new RuntimeException('Choose a supported online payment method');return $this->startPayment($orderId,$channel,$data,$actor);
    }

    public function pointOfSaleOptions(): array
    {
        $products=$this->db->query("SELECT p.id,p.title,p.item_id FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_products") . " p WHERE p.status='active' ORDER BY p.title")->fetchAll(PDO::FETCH_ASSOC);$sizes=$this->db->query("SELECT p.id product_id,NULL variant_id,us.id size_id,us.size,us.size_label,us.unit_price,GREATEST(0,us.quantity_available-us.quantity_reserved) available FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_products") . " p JOIN " . ReadReplicaService::qualifiedRef("uniform_sizes") . " us ON us.item_id=p.item_id WHERE p.status='active' UNION ALL SELECT v.product_id,v.id,us.id,us.size,us.size_label,us.unit_price,GREATEST(0,us.quantity_available-us.quantity_reserved) FROM uniform_catalog_variants v JOIN " . ReadReplicaService::qualifiedRef("uniform_sizes") . " us ON us.item_id=v.item_id JOIN " . ReadReplicaService::qualifiedRef("uniform_catalog_products") . " p ON p.id=v.product_id WHERE p.status='active' AND v.status='active'")->fetchAll(PDO::FETCH_ASSOC);foreach($products as &$p)$p['sizes']=array_values(array_filter($sizes,fn($s)=>(int)$s['product_id']===(int)$p['id']));unset($p);$staff=$this->db->query("SELECT u.user_id AS id,CONCAT(u.first_name,' ',u.last_name) name,u.username FROM " . ReadReplicaService::qualifiedRef('staff_directory') . " u WHERE u.user_status='active' AND u.staff_status='active' ORDER BY u.first_name,u.last_name")->fetchAll(PDO::FETCH_ASSOC);$students=$this->db->query("SELECT s.student_id AS id,s.admission_no,CONCAT_WS(' ',s.first_name,s.last_name) name FROM " . ReadReplicaService::qualifiedRef('person_directory') . " s WHERE s.student_status='active' ORDER BY s.first_name,s.last_name LIMIT 2000")->fetchAll(PDO::FETCH_ASSOC);return ['products'=>$products,'staff'=>$staff,'students'=>$students,'payment_options'=>$this->paymentOptions(true)];
    }

    public function pointOfSale(array $data,int $actor): array
    {
        $channel=(string)($data['channel']??'cash');if(!in_array($channel,['cash','bank_transfer','cheque'],true))throw new RuntimeException('Counter sales require cash, bank transfer or cheque confirmation');$paymentReference=trim((string)($data['payment_reference']??''));if($channel!=='cash'&&$paymentReference==='')throw new RuntimeException('Bank and cheque sales require the external payment reference');$account=(new FinancialAccountService($this->db))->requireFor((int)($data['financial_account_id']??0),'uniforms',$channel);$staffBuyer=(int)($data['staff_buyer_id']??0);$studentId=(int)($data['student_id']??0)?:null;$codes=array_values(array_unique(array_filter(array_map(fn($v)=>strtoupper(trim((string)$v)),(array)($data['unit_codes']??[])))));if(!$codes)throw new RuntimeException('Scan every physical item before completing the sale');
        $this->db->beginTransaction();try{$stockService=new CatalogStockService($this->db);$units=[];$grouped=[];foreach($codes as $code){$unit=$stockService->lookup($code,0,null,false);$lock=$this->db->prepare('SELECT status FROM catalog_stock_units WHERE id=? FOR UPDATE');$lock->execute([$unit['id']]);if($lock->fetchColumn()!=='in_stock')throw new RuntimeException($code.' is not available for sale');$key=$unit['product_id'].'|'.($unit['variant_id']?:0).'|'.$unit['size_id'];$units[$key][]=$unit;}
            $lines=[];$subtotal=0.0;foreach($units as $group){$first=$group[0];$line=$this->purchasableLine((int)$first['product_id'],(int)$first['variant_id']?:null,(int)$first['size_id'],'staff',true);$qty=count($group);if((int)$line['quantity_available']-(int)$line['quantity_reserved']<$qty)throw new RuntimeException($line['title'].' aggregate stock does not match its scanned units');$line['quantity']=$qty;$line['line_total']=$qty*(float)$line['unit_price'];$subtotal+=(float)$line['line_total'];$lines[]=['stock'=>$line,'units'=>$group];}
            $buyerType=$staffBuyer?'staff':'walk_in';$quote=$stockService->quoteDiscount($data['discount_code']??null,'physical',$subtotal,array_column($lines,'stock'),$buyerType,$staffBuyer?:null);$discount=(float)($quote['amount']??0);$total=max(0,$subtotal-$discount);$ref='KPS-POS-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(4)));
            $this->db->prepare("INSERT INTO catalog_orders(order_reference,buyer_type,buyer_id,student_id,source,status,payment_status,subtotal,discount_total,total_amount,customer_note,placed_by,paid_at,fulfilled_at) VALUES(?,?,?,?,'physical','fulfilled','paid',?,?,?,?,?,NOW(),NOW())")->execute([$ref,$buyerType,$staffBuyer?:null,$studentId,$subtotal,$discount,$total,$data['note']??null,$actor]);$orderId=(int)$this->db->lastInsertId();
            $insert=$this->db->prepare('INSERT INTO catalog_order_items(order_id,product_id,variant_id,size_id,item_id,product_title,variant_name,size_label,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?,?,?,?,?,?)');foreach($lines as $entry){$line=$entry['stock'];$insert->execute([$orderId,$line['product_id'],$line['variant_id']?:null,$line['size_id'],$line['item_id'],$line['title'],$line['variant_name'],$line['size_label']?:$line['size'],$line['quantity'],$line['unit_price'],$line['line_total']]);$lineId=(int)$this->db->lastInsertId();foreach($entry['units'] as $unit){$this->db->prepare("UPDATE catalog_stock_units SET status='dispatched',reserved_order_id=?,order_item_id=?,dispatched_by=?,dispatched_at=NOW() WHERE id=? AND status='in_stock'")->execute([$orderId,$lineId,$actor,$unit['id']]);$this->db->prepare("INSERT INTO catalog_stock_unit_events(unit_id,event_type,from_status,to_status,order_id,order_item_id,scanner_reference,notes,actor_user_id) VALUES(?,'dispatched','in_stock','dispatched',?,?,?,?,?)")->execute([$unit['id'],$orderId,$lineId,$data['scanner_reference']??null,'Physical counter sale '.$ref,$actor]);}$this->db->prepare('UPDATE uniform_sizes SET quantity_available=quantity_available-?,quantity_sold=quantity_sold+? WHERE id=?')->execute([$line['quantity'],$line['quantity'],$line['size_id']]);$this->db->prepare('UPDATE inventory_items SET current_quantity=GREATEST(0,current_quantity-?) WHERE id=?')->execute([$line['quantity'],$line['item_id']]);if($studentId)$this->db->prepare("INSERT INTO uniform_sales(student_id,item_id,size,quantity,unit_price,payment_status,sale_date,received_date,receipt_no,sold_by,notes) VALUES(?,?,?,?,?,'paid',CURDATE(),CURDATE(),?,?,?)")->execute([$studentId,$line['item_id'],$line['size_label']?:$line['size'],$line['quantity'],$line['unit_price'],$ref.'-'.$lineId,$actor,'Scanned physical sale '.$ref]);}
            if($quote)$stockService->recordDiscount($orderId,$quote,$buyerType,$staffBuyer?:null,$actor);$this->db->prepare("INSERT INTO catalog_payment_attempts(order_id,channel,amount,status,idempotency_reference,provider_transaction_id,financial_account_id,request_json,created_by,confirmed_at) VALUES(?,?,?,'confirmed',?,?,?,?,?,NOW())")->execute([$orderId,$channel,$total,$ref,trim((string)($data['payment_reference']??$ref)),(int)$account['id'],json_encode(['scanner_reference'=>$data['scanner_reference']??null,'unit_count'=>count($codes),'discount_code'=>$data['discount_code']??null]),$actor]);$paymentId=(int)$this->db->lastInsertId();$this->event($orderId,'point_of_sale',null,'fulfilled',$data['note']??null,$actor);(new FinancialPostingCoordinator($this->db))->postIncoming('catalog_payment_attempt',$paymentId,(int)$account['id'],'uniforms',(string)$total,$actor,(string)($data['payment_reference']??$ref));$this->db->commit();Logger::audit('catalog_point_of_sale','catalog_order',$orderId,'Scanned physical catalogue sale completed',['order_reference'=>$ref,'unit_codes'=>$codes,'subtotal'=>$subtotal,'discount'=>$discount,'amount'=>$total,'channel'=>$channel,'staff_buyer_id'=>$staffBuyer?:null,'student_id'=>$studentId]);return $this->order($orderId);}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }

    public function confirmByReference(string $reference,float $amount,string $provider,string $providerRef,int $actor=0): bool
    {
        $normalized=(new ReferenceNormalizer())->reference($reference);$s=$this->db->prepare('SELECT * FROM catalog_payment_attempts WHERE idempotency_reference=? OR idempotency_reference=? LIMIT 1');$s->execute([$reference,$normalized]);$payment=$s->fetch(PDO::FETCH_ASSOC);if(!$payment)return false;if($payment['status']==='confirmed')return true;if(abs((float)$payment['amount']-$amount)>.01)return false;$this->confirmOrder((int)$payment['order_id'],(int)$payment['id'],$providerRef,$actor);return true;
    }

    public function confirmOrder(int $orderId,int $paymentId,string $providerRef,int $actor=0): array
    {
        $this->db->beginTransaction();try{$s=$this->db->prepare('SELECT * FROM catalog_orders WHERE id=? FOR UPDATE');$s->execute([$orderId]);$order=$s->fetch(PDO::FETCH_ASSOC);if(!$order)throw new RuntimeException('Order not found');if($order['payment_status']==='paid'){$this->db->commit();return $order;}$lines=$this->db->prepare('SELECT * FROM catalog_order_items WHERE order_id=?');$lines->execute([$orderId]);$rows=$lines->fetchAll(PDO::FETCH_ASSOC);foreach($rows as $line){$stock=$this->db->prepare('SELECT quantity_available,quantity_reserved FROM uniform_sizes WHERE id=? FOR UPDATE');$stock->execute([$line['size_id']]);$q=$stock->fetch(PDO::FETCH_ASSOC);if(!$q||(int)$q['quantity_available']<(int)$line['quantity']||(int)$q['quantity_reserved']<(int)$line['quantity'])throw new RuntimeException('Reserved stock is inconsistent for '.$line['product_title']);}
            $this->db->prepare("UPDATE catalog_orders SET status='paid',payment_status='paid',paid_at=NOW() WHERE id=?")->execute([$orderId]);$this->db->prepare("UPDATE catalog_payment_attempts SET status='confirmed',provider_transaction_id=?,confirmed_at=NOW() WHERE id=?")->execute([$providerRef,$paymentId]);$this->event($orderId,'payment_confirmed',$order['status'],'paid',$providerRef,$actor);$payment=$this->payment($paymentId);if(!empty($payment['financial_account_id']))(new FinancialPostingCoordinator($this->db))->postIncoming('catalog_payment_attempt',$paymentId,(int)$payment['financial_account_id'],'uniforms',(string)$order['total_amount'],$actor,$providerRef);$this->db->commit();Logger::audit('catalog_payment_confirmed','catalog_order',$orderId,'Catalogue payment confirmed',['order_reference'=>$order['order_reference'],'amount'=>$order['total_amount'],'provider'=>$payment['channel']??null]);return $this->order($orderId);
        }catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }

    public function cancel(int $orderId,string $type,int $buyerId,int $actor=0): array
    {
        $this->db->beginTransaction();try{$s=$this->db->prepare('SELECT * FROM catalog_orders WHERE id=? FOR UPDATE');$s->execute([$orderId]);$o=$s->fetch(PDO::FETCH_ASSOC);if(!$o||($o['buyer_type']!==$type||(int)$o['buyer_id']!==$buyerId))throw new RuntimeException('Order not found');if(!in_array($o['status'],['pending_payment','payment_processing'],true))throw new RuntimeException('This order can no longer be cancelled');$lines=$this->db->prepare('SELECT size_id,quantity FROM catalog_order_items WHERE order_id=?');$lines->execute([$orderId]);foreach($lines as $line)$this->db->prepare('UPDATE uniform_sizes SET quantity_reserved=GREATEST(0,quantity_reserved-?) WHERE id=?')->execute([$line['quantity'],$line['size_id']]);$this->db->prepare("UPDATE catalog_orders SET status='cancelled',payment_status=IF(payment_status='paid','refunded','failed') WHERE id=?")->execute([$orderId]);$this->event($orderId,'order_cancelled',$o['status'],'cancelled',null,$actor);$this->db->commit();Logger::audit('catalog_order_cancelled','catalog_order',$orderId,'Catalogue order cancelled and reservations released',['order_reference'=>$o['order_reference'],'buyer_type'=>$type,'buyer_id'=>$buyerId]);return $this->order($orderId);}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }

    public function orders(string $type,int $buyerId): array { $this->buyer($type,$buyerId);$s=$this->db->prepare('SELECT * FROM catalog_orders WHERE buyer_type=? AND buyer_id=? ORDER BY created_at DESC');$s->execute([$type,$buyerId]);$rows=$s->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$r)$r['items']=$this->orderItems((int)$r['id']);return $rows; }
    public function order(int $id): array { $s=$this->db->prepare('SELECT * FROM catalog_orders WHERE id=?');$s->execute([$id]);$o=$s->fetch(PDO::FETCH_ASSOC);if(!$o)throw new RuntimeException('Order not found');$o['items']=$this->orderItems($id);return $o; }
    private function orderItems(int $id): array {$s=$this->db->prepare('SELECT * FROM catalog_order_items WHERE order_id=? ORDER BY id');$s->execute([$id]);return $s->fetchAll(PDO::FETCH_ASSOC);}
    private function payment(int $id): array {$s=$this->db->prepare('SELECT * FROM catalog_payment_attempts WHERE id=?');$s->execute([$id]);return $s->fetch(PDO::FETCH_ASSOC)?:[];}
    private function event(int $id,string $type,?string $from,?string $to,?string $note,int $actor): void {$this->db->prepare('INSERT INTO catalog_order_events(order_id,event_type,from_status,to_status,note,actor_user_id) VALUES(?,?,?,?,?,?)')->execute([$id,$type,$from,$to,$note,$actor?:null]);}

    public function reviews(int $productId): array
    {
        $s=$this->db->prepare("SELECT r.id,r.rating,r.title,r.comment,r.verified_purchase,r.created_at,r.buyer_type,CASE WHEN r.buyer_type='parent' THEN COALESCE((SELECT CONCAT(pe.first_name,' ',LEFT(pe.last_name,1),'.') FROM " . ReadReplicaService::qualifiedRef('person_directory') . " pe WHERE pe.parent_id=r.buyer_id),'Parent') ELSE COALESCE((SELECT CONCAT(pe.first_name,' ',LEFT(pe.last_name,1),'.') FROM " . ReadReplicaService::qualifiedRef('person_directory') . " pe WHERE pe.user_id=r.buyer_id),'Staff member') END reviewer_name,(SELECT COUNT(*) FROM catalog_review_helpful h WHERE h.review_id=r.id) helpful_count FROM " . ReadReplicaService::qualifiedRef("catalog_reviews") . " r WHERE r.product_id=? AND r.status='published' ORDER BY r.created_at DESC");$s->execute([$productId]);return $s->fetchAll(PDO::FETCH_ASSOC);
    }
    public function saveReview(string $type,int $buyerId,array $data): array
    {
        $this->buyer($type,$buyerId);$product=(int)($data['product_id']??0);$rating=(int)($data['rating']??0);if($rating<1||$rating>5)throw new RuntimeException('Rating must be between 1 and 5');$this->product($product,$type);$v=$this->db->prepare("SELECT 1 FROM " . ReadReplicaService::qualifiedRef("catalog_orders") . " JOIN " . ReadReplicaService::qualifiedRef("catalog_order_items") . " oi ON oi.order_id=o.id WHERE o.buyer_type=? AND o.buyer_id=? AND oi.product_id=? AND o.payment_status='paid' LIMIT 1");$v->execute([$type,$buyerId,$product]);$verified=$v->fetchColumn()?1:0;$this->db->prepare("INSERT INTO catalog_reviews(product_id,buyer_type,buyer_id,rating,title,comment,status,verified_purchase) VALUES(?,?,?,?,?,?,'pending',?) ON DUPLICATE KEY UPDATE rating=VALUES(rating),title=VALUES(title),comment=VALUES(comment),status='pending',verified_purchase=VALUES(verified_purchase),updated_at=NOW()")->execute([$product,$type,$buyerId,$rating,trim((string)($data['title']??''))?:null,trim((string)($data['comment']??''))?:null,$verified]);Logger::audit('catalog_review_submitted','catalog_product',$product,'Product review submitted for moderation',['buyer_type'=>$type,'buyer_id'=>$buyerId,'rating'=>$rating,'verified_purchase'=>(bool)$verified]);return ['submitted'=>true,'status'=>'pending','verified_purchase'=>(bool)$verified];
    }

    public function management(array $filters=[]): array
    {
        $where='1=1';$args=[];
        if(!empty($filters['status'])){$where.=' AND o.status=?';$args[]=$filters['status'];}
        $s=$this->db->prepare("SELECT o.*,CASE WHEN o.buyer_type='staff' THEN (SELECT CONCAT(p.first_name,' ',p.last_name) FROM " . ReadReplicaService::qualifiedRef('person_directory') . " p WHERE p.user_id=o.buyer_id) WHEN o.buyer_type='parent' THEN (SELECT CONCAT(p.first_name,' ',p.last_name) FROM " . ReadReplicaService::qualifiedRef('person_directory') . " p WHERE p.parent_id=o.buyer_id) ELSE 'Walk-in customer' END buyer_name,(SELECT COUNT(*) FROM " . ReadReplicaService::qualifiedRef("catalog_order_items") . " oi WHERE oi.order_id=o.id) line_count FROM " . ReadReplicaService::qualifiedRef("catalog_orders") . " o WHERE $where ORDER BY o.created_at DESC LIMIT 500");
        $s->execute($args);$orders=$s->fetchAll(PDO::FETCH_ASSOC);foreach($orders as &$order)$order['items']=$this->orderItems((int)$order['id']);unset($order);
        $summary=$this->db->query("SELECT COUNT(*) orders,COALESCE(SUM(subtotal),0) gross_value,COALESCE(SUM(discount_total),0) discounts_given,COALESCE(SUM(total_amount),0) value,COALESCE(SUM(payment_status='paid'),0) paid_orders,COALESCE(SUM(status IN ('paid','preparing','ready')),0) awaiting_fulfilment,COALESCE(SUM(source='online'),0) online_orders,COALESCE(SUM(source='internal'),0) internal_orders,COALESCE(SUM(source='physical'),0) physical_orders FROM catalog_orders")->fetch(PDO::FETCH_ASSOC);
        $legacy=$this->db->query("SELECT COUNT(*) physical_sales,COALESCE(SUM(quantity*unit_price),0) physical_value FROM uniform_sales")->fetch(PDO::FETCH_ASSOC);
        $engagement=$this->db->query("SELECT (SELECT COUNT(*) FROM " . ReadReplicaService::qualifiedRef("catalog_wishlists") . ") wishlist_count,(SELECT COUNT(*) FROM " . ReadReplicaService::qualifiedRef("catalog_reviews") . " WHERE status='pending') pending_reviews,(SELECT ROUND(AVG(rating),2) FROM " . ReadReplicaService::qualifiedRef("catalog_reviews") . " WHERE status='published') average_rating")->fetch(PDO::FETCH_ASSOC);
        $reviews=$this->db->query("SELECT r.*,p.title product_title,CASE WHEN r.buyer_type='parent' THEN 'Parent' ELSE 'Staff member' END reviewer_type FROM " . ReadReplicaService::qualifiedRef("catalog_reviews") . " JOIN " . ReadReplicaService::qualifiedRef("uniform_catalog_products") . " p ON p.id=r.product_id WHERE r.status='pending' ORDER BY r.created_at LIMIT 100")->fetchAll(PDO::FETCH_ASSOC);
        $products=$this->db->query("SELECT p.id,p.title,(SELECT COUNT(*) FROM " . ReadReplicaService::qualifiedRef("catalog_wishlists") . " w WHERE w.product_id=p.id) wishlist_count,(SELECT COUNT(*) FROM " . ReadReplicaService::qualifiedRef("catalog_reviews") . " r WHERE r.product_id=p.id AND r.status='published') review_count,(SELECT ROUND(AVG(r.rating),2) FROM " . ReadReplicaService::qualifiedRef("catalog_reviews") . " r WHERE r.product_id=p.id AND r.status='published') rating,(SELECT COALESCE(SUM(oi.quantity),0) FROM " . ReadReplicaService::qualifiedRef("catalog_order_items") . " oi JOIN " . ReadReplicaService::qualifiedRef("catalog_orders") . " o ON o.id=oi.order_id WHERE oi.product_id=p.id AND o.payment_status='paid') units_sold,(SELECT COALESCE(SUM(us.quantity_available),0) FROM " . ReadReplicaService::qualifiedRef("uniform_sizes") . " us WHERE us.item_id=p.item_id OR us.item_id IN (SELECT v.item_id FROM uniform_catalog_variants v WHERE v.product_id=p.id AND v.status='active')) available_stock,(SELECT COALESCE(SUM(us.quantity_reserved),0) FROM " . ReadReplicaService::qualifiedRef("uniform_sizes") . " us WHERE us.item_id=p.item_id OR us.item_id IN (SELECT v.item_id FROM uniform_catalog_variants v WHERE v.product_id=p.id AND v.status='active')) reserved_stock FROM " . ReadReplicaService::qualifiedRef("uniform_catalog_products") . " p ORDER BY units_sold DESC,wishlist_count DESC LIMIT 100")->fetchAll(PDO::FETCH_ASSOC);
        return ['orders'=>$orders,'summary'=>array_merge($summary,$legacy),'engagement'=>$engagement,'pending_reviews'=>$reviews,'product_analytics'=>$products];
    }

    public function scanOrderUnit(int $orderId,string $code,int $actor,?string $scanner=null): array
    {
        $this->db->beginTransaction();try{$orderStmt=$this->db->prepare('SELECT * FROM catalog_orders WHERE id=? FOR UPDATE');$orderStmt->execute([$orderId]);$order=$orderStmt->fetch(PDO::FETCH_ASSOC);if(!$order)throw new RuntimeException('Order not found');if($order['source']==='physical')throw new RuntimeException('Physical counter sales are scanned in Point of Sale');if($order['payment_status']!=='paid'||!in_array($order['status'],['paid','preparing','ready'],true))throw new RuntimeException('Only paid orders awaiting fulfilment can be packed');$stock=new CatalogStockService($this->db);$unit=$stock->lookup($code,0,null,false);$lock=$this->db->prepare('SELECT status,reserved_order_id FROM catalog_stock_units WHERE id=? FOR UPDATE');$lock->execute([$unit['id']]);$state=$lock->fetch(PDO::FETCH_ASSOC);if($state['status']==='reserved'&&(int)$state['reserved_order_id']===$orderId){$this->db->commit();return $this->orderPacking($orderId);}if($state['status']!=='in_stock')throw new RuntimeException($unit['unit_code'].' is already reserved, dispatched, or unavailable');$line=$this->db->prepare('SELECT oi.*,COUNT(su.id) scanned FROM catalog_order_items oi LEFT JOIN catalog_stock_units su ON su.order_item_id=oi.id AND su.status=\'reserved\' WHERE oi.order_id=? AND oi.product_id=? AND oi.size_id=? AND oi.variant_id <=> ? GROUP BY oi.id HAVING scanned<oi.quantity ORDER BY oi.id LIMIT 1 FOR UPDATE');$line->execute([$orderId,$unit['product_id'],$unit['size_id'],$unit['variant_id']?:null]);$item=$line->fetch(PDO::FETCH_ASSOC);if(!$item)throw new RuntimeException('This scanned product/variant/size is not required, or its quantity is already packed');$this->db->prepare("UPDATE catalog_stock_units SET status='reserved',reserved_order_id=?,order_item_id=? WHERE id=?")->execute([$orderId,$item['id'],$unit['id']]);$this->db->prepare("INSERT INTO catalog_stock_unit_events(unit_id,event_type,from_status,to_status,order_id,order_item_id,scanner_reference,notes,actor_user_id) VALUES(?,'reserved','in_stock','reserved',?,?,?,?,?)")->execute([$unit['id'],$orderId,$item['id'],$scanner,'Packed for '.$order['order_reference'],$actor]);if($order['status']==='paid'){$this->db->prepare("UPDATE catalog_orders SET status='preparing' WHERE id=?")->execute([$orderId]);$this->event($orderId,'packing_started','paid','preparing',null,$actor);}$this->db->commit();Logger::audit('catalog_order_unit_scanned','catalog_order',$orderId,'Physical unit assigned to paid order',['order_reference'=>$order['order_reference'],'unit_code'=>$unit['unit_code'],'order_item_id'=>$item['id']]);return $this->orderPacking($orderId);}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }

    public function orderPacking(int $orderId): array
    {
        $order=$this->order($orderId);$stmt=$this->db->prepare("SELECT oi.id,oi.product_title,oi.variant_name,oi.size_label,oi.quantity,COUNT(u.id) scanned FROM " . ReadReplicaService::qualifiedRef("catalog_order_items") . " LEFT JOIN " . ReadReplicaService::qualifiedRef("catalog_stock_units") . " u ON u.order_item_id=oi.id AND u.status='reserved' WHERE oi.order_id=? GROUP BY oi.id ORDER BY oi.id");$stmt->execute([$orderId]);$lines=$stmt->fetchAll(PDO::FETCH_ASSOC);$required=0;$scanned=0;foreach($lines as $line){$required+=(int)$line['quantity'];$scanned+=(int)$line['scanned'];}$order['packing_lines']=$lines;$order['required_units']=$required;$order['scanned_units']=$scanned;$order['complete']=$required>0&&$required===$scanned;return $order;
    }

    public function dispatchOrder(int $orderId,int $actor,?string $note=null): array
    {
        $this->db->beginTransaction();try{$stmt=$this->db->prepare('SELECT * FROM catalog_orders WHERE id=? FOR UPDATE');$stmt->execute([$orderId]);$order=$stmt->fetch(PDO::FETCH_ASSOC);if(!$order)throw new RuntimeException('Order not found');if($order['source']==='physical'&&$order['status']==='fulfilled'){$this->db->commit();return $this->order($orderId);}if($order['payment_status']!=='paid'||!in_array($order['status'],['paid','preparing','ready'],true))throw new RuntimeException('Only paid orders awaiting fulfilment can be dispatched');$lines=$this->db->prepare('SELECT * FROM catalog_order_items WHERE order_id=? FOR UPDATE');$lines->execute([$orderId]);$rows=$lines->fetchAll(PDO::FETCH_ASSOC);foreach($rows as $line){$count=$this->db->prepare("SELECT COUNT(*) FROM catalog_stock_units WHERE order_item_id=? AND reserved_order_id=? AND status='reserved' FOR UPDATE");$count->execute([$line['id'],$orderId]);if((int)$count->fetchColumn()!==(int)$line['quantity'])throw new RuntimeException('Scan every unit for '.$line['product_title'].' · '.$line['size_label'].' before dispatch');}
            foreach($rows as $line){$units=$this->db->prepare("SELECT id,unit_code FROM catalog_stock_units WHERE order_item_id=? AND reserved_order_id=? AND status='reserved' FOR UPDATE");$units->execute([$line['id'],$orderId]);foreach($units->fetchAll(PDO::FETCH_ASSOC) as $unit){$this->db->prepare("UPDATE catalog_stock_units SET status='dispatched',dispatched_by=?,dispatched_at=NOW() WHERE id=?")->execute([$actor,$unit['id']]);$this->db->prepare("INSERT INTO catalog_stock_unit_events(unit_id,event_type,from_status,to_status,order_id,order_item_id,notes,actor_user_id) VALUES(?,'dispatched','reserved','dispatched',?,?,?,?)")->execute([$unit['id'],$orderId,$line['id'],$note?:'Released against '.$order['order_reference'],$actor]);}$this->db->prepare('UPDATE uniform_sizes SET quantity_available=quantity_available-?,quantity_reserved=GREATEST(0,quantity_reserved-?),quantity_sold=quantity_sold+? WHERE id=?')->execute([$line['quantity'],$line['quantity'],$line['quantity'],$line['size_id']]);$this->db->prepare('UPDATE inventory_items SET current_quantity=GREATEST(0,current_quantity-?) WHERE id=?')->execute([$line['quantity'],$line['item_id']]);if(!empty($order['student_id']))$this->db->prepare("INSERT INTO uniform_sales(student_id,item_id,size,quantity,unit_price,payment_status,sale_date,received_date,receipt_no,sold_by,notes) VALUES(?,?,?,?,?,'paid',CURDATE(),CURDATE(),?,?,?)")->execute([$order['student_id'],$line['item_id'],$line['size_label'],$line['quantity'],$line['unit_price'],$order['order_reference'].'-'.$line['id'],$actor,'Scanned catalogue dispatch '.$order['order_reference']]);}
            $this->db->prepare("UPDATE catalog_orders SET status='fulfilled',fulfilled_at=NOW() WHERE id=?")->execute([$orderId]);$this->event($orderId,'order_dispatched',$order['status'],'fulfilled',$note,$actor);$this->db->commit();Logger::audit('catalog_order_dispatched','catalog_order',$orderId,'Paid order released after complete unit scan',['order_reference'=>$order['order_reference'],'unit_count'=>array_sum(array_map(fn($line)=>(int)$line['quantity'],$rows))]);return $this->order($orderId);}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }

    public function updateOrderStatus(int $id,string $status,int $actor,?string $note=null): array
    {
        if(!in_array($status,['preparing','ready','fulfilled','cancelled'],true))throw new RuntimeException('Invalid fulfilment status');$o=$this->order($id);if($status==='cancelled')return $this->cancel($id,$o['buyer_type'],(int)$o['buyer_id'],$actor);if($status==='fulfilled')return $this->dispatchOrder($id,$actor,$note);if($o['payment_status']!=='paid')throw new RuntimeException('Only paid orders can enter fulfilment');$this->db->prepare('UPDATE catalog_orders SET status=? WHERE id=?')->execute([$status,$id]);$this->event($id,'status_changed',$o['status'],$status,$note,$actor);Logger::audit('catalog_order_status_changed','catalog_order',$id,'Catalogue fulfilment status changed',['from'=>$o['status'],'to'=>$status]);return $this->order($id);
    }

    public function moderateReview(int $id,string $status,int $actor): array { if(!in_array($status,['published','rejected'],true))throw new RuntimeException('Invalid review decision');$this->db->prepare('UPDATE catalog_reviews SET status=?,moderated_by=?,moderated_at=NOW() WHERE id=?')->execute([$status,$actor,$id]);Logger::audit('catalog_review_moderated','catalog_review',$id,'Product review moderation completed',['decision'=>$status]);return ['id'=>$id,'status'=>$status]; }
}
