<?php
/** Professional self-service account settings. */
?>
<link rel="stylesheet" href="<?= htmlspecialchars($appBase) ?>/css/pages/account-center.css?v=<?= asset_version('css/pages/account-center.css') ?>">
<style>
    .settings-shell { max-width: 1260px; margin: 0 auto; }
    .settings-hero { background: linear-gradient(120deg, #0f5b3b, #173d34 62%, #d3ad24); color: #fff; border: 0; overflow: hidden; }
    .settings-hero .hero-pattern { opacity: .12; font-size: 11rem; line-height: .7; transform: rotate(-12deg); }
    .settings-nav .nav-link { color: #52605b; text-align: left; border-radius: .65rem; padding: .7rem .85rem; font-weight: 600; }
    .settings-nav .nav-link:hover { background: #edf6f1; color: #0f5b3b; }
    .settings-nav .nav-link.active { background: #0f5b3b; color: #fff; box-shadow: 0 5px 14px rgba(15,91,59,.18); }
    .settings-nav .nav-link i { width: 1.35rem; }
    .settings-section { scroll-margin-top: 1rem; }
    .settings-tile { border: 1px solid #e8eeeb; transition: transform .18s, box-shadow .18s; }
    .settings-tile:hover { transform: translateY(-2px); box-shadow: 0 .5rem 1.2rem rgba(20,45,35,.08)!important; }
    .settings-icon { width: 42px; height: 42px; display: inline-flex; align-items: center; justify-content: center; border-radius: 12px; font-size: 1.2rem; }
    .settings-muted { color: #6b7a74; }
    .security-score { height: 8px; }
    @media (max-width: 767.98px) { .settings-nav { display:flex; overflow:auto; flex-wrap:nowrap; gap:.35rem; padding-bottom:.5rem; } .settings-nav .nav-link { white-space:nowrap; } .settings-nav .nav-link span { display:none; } }
</style>

<div class="container-fluid px-3 px-lg-4 py-3" id="accountSettingsPage">
    <div class="settings-shell">
        <header class="card settings-hero shadow-sm mb-3">
            <div class="account-cover" aria-hidden="true"><span class="account-cover-mark"><i class="bi bi-shield-check"></i></span></div>
            <div class="account-identity-bar">
                <div id="settings-avatar" class="account-avatar">U</div>
                <div class="account-identity-copy"><p class="small text-success fw-semibold mb-1">Account centre</p><h1 class="h3 mb-1" id="settings-name">Your account</h1><p class="mb-0 text-muted" id="settings-email">Loading account details…</p></div>
                <div class="account-identity-meta"><span class="badge rounded-pill bg-success-subtle text-success px-3 py-2" id="settings-role">Staff account</span><button class="btn btn-success btn-sm" type="button" data-settings-target="profile"><i class="bi bi-pencil-square me-1"></i>Edit profile</button></div>
            </div>
        </header>

        <div class="row g-4 align-items-start account-workspace">
            <aside class="col-lg-3 col-xl-2">
                <div class="card border-0 shadow-sm sticky-lg-top" style="top:1rem">
                    <div class="card-body p-2 settings-nav nav flex-lg-column" role="tablist">
                        <p class="settings-nav-title">Profile information</p>
                        <button class="nav-link active" data-settings-target="profile" type="button"><i class="bi bi-person"></i><span>Personal information</span></button>
                        <button class="nav-link" data-settings-target="activity" type="button"><i class="bi bi-clock-history"></i><span>Login activity</span></button>
                        <button class="nav-link" data-settings-target="security" type="button"><i class="bi bi-shield-lock"></i><span>Security</span></button>
                        <button class="nav-link" data-settings-target="privacy" type="button"><i class="bi bi-fingerprint"></i><span>Privacy centre</span></button>
                        <button class="nav-link" data-settings-target="legal" type="button"><i class="bi bi-file-earmark-text"></i><span>Terms & policies</span></button>
                    </div>
                </div>
            </aside>

            <main class="col-lg-9 col-xl-10">
                <section class="settings-section d-none" data-settings-section="overview">
                    <div class="d-flex justify-content-between align-items-end mb-3"><div><h2 class="h4 mb-1">Good to see you</h2><p class="settings-muted mb-0">A quick view of your account health and important actions.</p></div></div>
                    <div class="row g-3 mb-4">
                        <div class="col-md-4"><div class="card settings-tile shadow-sm h-100"><div class="card-body"><div class="settings-icon bg-success-subtle text-success mb-3"><i class="bi bi-person-check"></i></div><h3 class="h6">Profile</h3><p class="small settings-muted mb-3">Keep your contact details current for school communication.</p><button class="btn btn-sm btn-outline-success" data-settings-target="profile">View profile</button></div></div></div>
                        <div class="col-md-4"><div class="card settings-tile shadow-sm h-100"><div class="card-body"><div class="settings-icon bg-primary-subtle text-primary mb-3"><i class="bi bi-shield-check"></i></div><h3 class="h6">Sign-in security</h3><p class="small settings-muted mb-2">Password, MFA, passkeys and recovery options.</p><span class="badge bg-secondary" id="overview-security-badge">Checking…</span><button class="btn btn-sm btn-outline-primary d-block mt-3" data-settings-target="security">Manage security</button></div></div></div>
                        <div class="col-md-4"><div class="card settings-tile shadow-sm h-100"><div class="card-body"><div class="settings-icon bg-warning-subtle text-warning mb-3"><i class="bi bi-fingerprint"></i></div><h3 class="h6">Privacy centre</h3><p class="small settings-muted mb-3">Understand how account and activity data is protected.</p><button class="btn btn-sm btn-outline-warning" data-settings-target="privacy">Review privacy</button></div></div></div>
                    </div>
                    <div class="card border-0 shadow-sm"><div class="card-body p-4"><h3 class="h6 mb-3">Account information</h3><div class="row g-3 small"><div class="col-md-4"><span class="settings-muted d-block">Name</span><strong id="settings-name-2">—</strong></div><div class="col-md-4"><span class="settings-muted d-block">Email</span><strong id="settings-email-2">—</strong></div><div class="col-md-4"><span class="settings-muted d-block">Phone</span><strong id="settings-phone">—</strong></div></div></div></div>
                </section>

                <section class="settings-section" data-settings-section="profile">
                    <div class="card border-0 shadow-sm account-completion mb-3"><div class="card-body py-3 px-4"><div class="d-flex flex-wrap align-items-center gap-3"><div class="flex-grow-1"><div class="d-flex justify-content-between small mb-2"><strong>Profile completion</strong><span class="text-success fw-bold" id="profileCompletionLabel">Checking…</span></div><div class="progress" role="progressbar" aria-label="Profile completion" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar bg-success" id="profileCompletionBar" style="width:0%"></div></div></div><div class="account-completion-note small text-muted"><i class="bi bi-info-circle me-1"></i>Complete your information to keep school communication reliable.</div></div></div></div>
                    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3"><div><h2 class="h4 mb-1">Personal information</h2><p class="settings-muted mb-0">Keep your identity and contact information accurate.</p></div><div class="d-flex gap-2"><button class="btn btn-outline-secondary d-none" id="profileCancelBtn" type="button">Cancel</button><button class="btn btn-success d-none" id="profileSaveBtn" type="button"><i class="bi bi-check2 me-1"></i>Save changes</button><button class="btn btn-outline-success" id="profileEditBtn" type="button"><i class="bi bi-pencil me-1"></i>Edit profile</button></div></div>
                    <div class="card border-0 shadow-sm"><div class="card-body p-4" id="personalInfoFields"><p class="text-muted small mb-0">Loading profile…</p></div></div>
                    <div class="d-none" aria-hidden="true"><div id="profileAvatar">U</div><span id="profileName">User</span><span id="profileEmail">—</span><span id="profileRole">User</span><span id="profileDomainBadge"></span><span id="profilePhone">—</span><span id="currentAcademicYear">—</span><span id="profileLastLogin">—</span></div>
                    <div class="mt-4 mb-3"><h2 class="h5 mb-1">Professional information</h2><p class="settings-muted mb-0">Official employment and statutory details maintained by the school.</p></div>
                    <div class="d-none"><span id="profileEmployeeId">—</span><span id="profileDepartment">—</span><span id="profileTenure">—</span></div>
                    <div class="d-none" id="profileEmployeeRow"></div><div class="d-none" id="profileDepartmentRow"></div><div class="d-none" id="profileTenureRow"></div>
                    <div class="card border-0 shadow-sm mb-3 d-none" id="employmentCard"><div class="card-header bg-white border-0 px-4 pt-4"><strong>Employment record</strong></div><div class="card-body p-4" id="employmentFields"></div></div>
                    <div class="card border-0 shadow-sm mb-3 d-none" id="systemProfessionalCard"><div class="card-body p-4"><div class="row g-3">
                        <div class="col-md-4"><label class="form-label small text-muted" for="systemProfessionalUsername">Username</label><input class="form-control" id="systemProfessionalUsername" readonly></div>
                        <div class="col-md-4"><label class="form-label small text-muted" for="systemProfessionalDomain">Account domain</label><input class="form-control" id="systemProfessionalDomain" value="System / Platform" readonly></div>
                        <div class="col-md-4"><label class="form-label small text-muted" for="systemProfessionalRole">Primary role</label><input class="form-control" id="systemProfessionalRole" readonly></div>
                    </div></div></div>
                    <div class="card border-0 shadow-sm mb-3 d-none" id="financialCard"><div class="card-header bg-white border-0 px-4 pt-4"><strong>Financial and statutory record</strong></div><div class="card-body p-4" id="financialFields"></div></div>
                    <div class="card border-0 shadow-sm d-none" id="kpiSection"><div class="card-header bg-white border-0 px-4 pt-4"><strong>Performance summary</strong></div><div class="card-body p-4" id="kpiSummary"></div></div>
                    <div class="card border-0 shadow-sm mt-3"><div class="card-header bg-white border-0 px-4 pt-4"><strong>Assigned roles</strong></div><div class="card-body px-4" id="rolesList"></div></div>
                </section>

                <section class="settings-section d-none" data-settings-section="activity">
                    <div class="d-flex justify-content-between align-items-start mb-3"><div><h2 class="h4 mb-1">Login activity</h2><p class="settings-muted mb-0">Review recent access and investigate anything you do not recognize.</p></div><a class="btn btn-outline-success btn-sm" href="home.php?route=active_sessions">Manage sessions</a></div>
                    <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0" id="loginHistoryTable"><thead><tr><th>Date & time</th><th>IP address</th><th>Device</th><th>Browser</th><th>Status</th></tr></thead><tbody><tr><td colspan="5" class="text-center text-muted py-4">Loading activity…</td></tr></tbody></table></div></div>
                </section>

                <section class="settings-section d-none" data-settings-section="security">
                    <div class="mb-3"><h2 class="h4 mb-1">Security</h2><p class="settings-muted mb-0">Protect your account and choose how you verify sign-ins.</p></div>
                    <div class="card border-0 shadow-sm mb-3"><div class="card-body p-4"><div class="d-flex justify-content-between gap-3"><div><h3 class="h6 mb-1"><i class="bi bi-key text-primary me-2"></i>Password</h3><p class="small settings-muted mb-0">Use a unique password and update it regularly.</p></div><button class="btn btn-outline-primary btn-sm" id="openPasswordModal"><i class="bi bi-pencil me-1"></i>Change password</button></div></div></div>
                    <div class="card border-0 shadow-sm mb-3" id="mfa-card"><div class="card-header bg-white border-0 pt-4 px-4 d-flex justify-content-between align-items-center"><div><h3 class="h6 mb-1"><i class="bi bi-shield-lock text-success me-2"></i>Multi-factor authentication</h3><p class="small settings-muted mb-0">Email OTP is the protected baseline. Add an authenticator or passkey for stronger and faster verification.</p></div><span id="tfa-status-badge" class="badge bg-secondary">Loading…</span></div><div class="card-body p-4"><div class="d-flex flex-wrap align-items-center gap-2 mb-3 small"><span class="settings-muted">Enabled methods:</span><strong id="tfa-method">—</strong></div><div id="tfa-setup-section"><div class="row g-2"><div class="col-sm-6 col-xl-3"><button class="btn btn-outline-primary w-100" id="tfa-setup-totp"><i class="bi bi-phone me-1"></i>Authenticator</button></div><div class="col-sm-6 col-xl-3"><button class="btn btn-outline-primary w-100" id="tfa-setup-email"><i class="bi bi-envelope me-1"></i>Email OTP</button></div><div class="col-sm-6 col-xl-3"><button class="btn btn-outline-secondary w-100" disabled title="Available after Africa's Talking is configured"><i class="bi bi-chat-dots me-1"></i>SMS (coming later)</button></div><div class="col-sm-6 col-xl-3"><button class="btn btn-outline-secondary w-100" disabled title="Available after Africa's Talking is configured"><i class="bi bi-whatsapp me-1"></i>WhatsApp (coming later)</button></div></div></div><div id="tfa-manage-section" class="d-none"><div id="tfa-passkeys-list" class="alert alert-light small"></div><button class="btn btn-outline-dark btn-sm me-2" id="tfa-setup-passkey"><i class="bi bi-person-badge me-1"></i>Add passkey</button><span class="small text-muted"><i class="bi bi-shield-check me-1"></i>Email protection cannot be disabled.</span></div><div id="tfa-verify-section" class="d-none mt-4 pt-4 border-top"><div id="tfa-qr-container" class="d-none mb-3"><p class="small settings-muted">Scan with Google Authenticator, Microsoft Authenticator or another TOTP app.</p><img id="tfa-qr-img" class="border rounded p-2" src="" alt="Authenticator setup QR" style="width:180px;height:180px"><p class="small mt-2 mb-0">Manual key: <code id="tfa-secret-display" class="user-select-all"></code></p></div><div class="input-group" style="max-width:420px"><input class="form-control" id="tfa-verify-code-input" placeholder="Enter verification code" inputmode="numeric" autocomplete="one-time-code"><button class="btn btn-primary" id="tfa-verify-code-btn">Verify & enable</button></div></div></div></div>
                    <div id="tfa-backup-section" class="card border-0 shadow-sm d-none"><div class="card-header bg-white border-0 pt-4 px-4 d-flex justify-content-between"><div><h3 class="h6 mb-1"><i class="bi bi-life-preserver text-warning me-2"></i>Recovery codes</h3><p class="small settings-muted mb-0">Single-use codes for when you cannot access your usual verification method.</p></div><button class="btn btn-outline-warning btn-sm" id="tfa-backup-generate-btn">Generate new</button></div><div class="card-body px-4 pb-4"><div id="tfa-backup-codes-display" class="d-none"></div></div></div>
                </section>

                <section class="settings-section d-none" data-settings-section="privacy">
                    <div class="mb-3"><h2 class="h4 mb-1">Privacy centre</h2><p class="settings-muted mb-0">Clear information about the data used to operate your account.</p></div>
                    <div class="row g-3"><div class="col-md-6"><div class="card settings-tile shadow-sm h-100"><div class="card-body p-4"><div class="settings-icon bg-success-subtle text-success mb-3"><i class="bi bi-lock"></i></div><h3 class="h6">Account protection</h3><p class="small settings-muted">Passwords, OTPs, authenticator secrets and passkeys are used only to protect access. Never share verification codes.</p><button class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target="#privacyDetailsModal">How we protect data</button></div></div></div><div class="col-md-6"><div class="card settings-tile shadow-sm h-100"><div class="card-body p-4"><div class="settings-icon bg-info-subtle text-info mb-3"><i class="bi bi-clock-history"></i></div><h3 class="h6">Activity and sessions</h3><p class="small settings-muted">Review account activity and sign out from sessions through the security administration page.</p><a class="btn btn-sm btn-outline-info" href="home.php?route=active_sessions">Review sessions</a></div></div></div></div>
                </section>

                <section class="settings-section d-none" data-settings-section="legal">
                    <div class="mb-3"><h2 class="h4 mb-1">Terms & policies</h2><p class="settings-muted mb-0">The rules and notices that govern use of Kingsway Preparatory School systems.</p></div>
                    <div class="list-group shadow-sm"><button class="list-group-item list-group-item-action p-4" data-bs-toggle="modal" data-bs-target="#termsModal"><i class="bi bi-file-earmark-check text-success fs-4 me-3"></i><strong>Terms of service</strong><span class="d-block small settings-muted ms-5">Acceptable use, responsibilities and account access.</span></button><button class="list-group-item list-group-item-action p-4" data-bs-toggle="modal" data-bs-target="#privacyDetailsModal"><i class="bi bi-shield-check text-primary fs-4 me-3"></i><strong>Privacy notice</strong><span class="d-block small settings-muted ms-5">How personal and operational data is handled.</span></button></div>
                </section>
            </main>
        </div>
    </div>
</div>

<div class="modal fade" id="passwordModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable modal-dialog-centered"><div class="modal-content"><form id="passwordChangeForm" autocomplete="off"><div class="modal-header"><h5 class="modal-title"><i class="bi bi-key text-primary me-2"></i>Change password</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="small settings-muted">Enter your current password, then choose a strong new password.</p><div class="mb-3"><label class="form-label" for="settings-current-password">Current password</label><input type="password" class="form-control" id="settings-current-password" required autocomplete="current-password"></div><div class="mb-3"><label class="form-label" for="settings-new-password">New password</label><input type="password" class="form-control" id="settings-new-password" required minlength="10" autocomplete="new-password"><div class="form-text">Use at least 10 characters.</div></div><div><label class="form-label" for="settings-confirm-password">Confirm new password</label><input type="password" class="form-control" id="settings-confirm-password" required autocomplete="new-password"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary" id="settings-password-btn">Update password</button></div></form></div></div></div>
<div class="modal fade" id="reauthModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-sm"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Confirm your identity</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><p class="small settings-muted">Enter your current password before changing security settings.</p><input type="password" class="form-control" id="reauth-password" autocomplete="current-password" placeholder="Current password"></div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" id="reauth-confirm">Continue</button></div></div></div></div>
<div class="modal fade" id="privacyDetailsModal" tabindex="-1"><div class="modal-dialog modal-dialog-scrollable modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Privacy notice</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body small"><p>We use account identity, contact details, authentication events and audit records to provide secure school services.</p><p>Security credentials such as passwords, recovery codes and authenticator secrets must never be displayed or shared. Delivery and activity records are restricted to authorized school roles.</p><p class="mb-0 text-muted">For correction or access requests, contact the school administrator.</p></div></div></div></div>
<div class="modal fade" id="termsModal" tabindex="-1"><div class="modal-dialog modal-dialog-scrollable modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Terms of service</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body small"><p>Use this system only for authorized school work. Keep credentials private, verify recipients before sending information, and report suspected account compromise immediately.</p><p class="mb-0 text-muted">The school may audit activity to protect learners, families and staff.</p></div></div></div></div>

<script src="<?= htmlspecialchars($appBase) ?>/js/pages/account_settings.js?v=<?= asset_version('js/pages/account_settings.js') ?>"></script>
<script src="<?= htmlspecialchars($appBase) ?>/js/pages/me.js?v=<?= asset_version('js/pages/me.js') ?>"></script>
