<?php /** Staff Leave — self-service and approval workspace */ ?>
<div class="container-fluid py-4" data-staff-page data-required-permission="staff.leave.request">
  <div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="mb-1"><i class="bi bi-calendar2-x me-2"></i>Staff Leave</h3><p class="text-muted mb-0">Request leave, review balances and process approvals.</p></div><button class="btn btn-primary" id="newLeaveBtn" data-permission="staff.leave.request,staff.leave.manage"><i class="bi bi-plus-lg me-1"></i>New Request</button></div>
  <div class="row g-3 mb-4"><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Pending</small><h3 id="leavePending">0</h3></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Approved</small><h3 id="leaveApproved">0</h3></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Rejected</small><h3 id="leaveRejected">0</h3></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Days Requested</small><h3 id="leaveDaysTotal">0</h3></div></div></div></div>
  <div class="card border-0 shadow-sm"><div class="card-header bg-white"><div class="row g-2"><div class="col-md-4"><input class="form-control" id="leaveSearch" placeholder="Search staff or leave type"></div><div class="col-md-3"><select id="leaveStatusFilter" class="form-select"><option value="">All statuses</option><option>pending</option><option>approved</option><option>rejected</option><option>cancelled</option></select></div><div class="col-md-2"><button id="refreshLeaveBtn" class="btn btn-outline-secondary w-100"><i class="bi bi-arrow-clockwise"></i> Refresh</button></div></div></div><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Staff</th><th>Leave Type</th><th>Dates</th><th>Days</th><th>Reason</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody id="leaveBody"><tr><td colspan="7" class="text-center py-4">Loading…</td></tr></tbody></table></div></div>
</div>
<div class="modal fade" id="leaveRequestModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">New Leave Request</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3" id="leaveStaffWrap" data-permission="staff.leave.manage"><label class="form-label">Staff member</label><select id="leaveStaffId" class="form-select"><option value="">Myself / selected staff</option></select></div><div class="mb-3"><label class="form-label">Leave type</label><select id="leaveTypeId" class="form-select" required><option value="">Select leave type</option></select></div><div class="row g-2"><div class="col"><label class="form-label">Start date</label><input id="leaveStart" type="date" class="form-control" required></div><div class="col"><label class="form-label">End date</label><input id="leaveEnd" type="date" class="form-control" required></div></div><div class="mt-3"><label class="form-label">Reason</label><textarea id="leaveReason" class="form-control" rows="3" required></textarea></div><div class="mt-3"><label class="form-label">Relief staff (optional)</label><select id="leaveReliefId" class="form-select"><option value="">None</option></select></div></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button id="submitLeaveBtn" class="btn btn-primary">Submit Request</button></div></div></div></div>
<div class="modal fade" id="leaveDecisionModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Leave Decision</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="decisionLeaveId"><label class="form-label">Decision</label><select id="leaveDecision" class="form-select"><option value="approved">Approve</option><option value="rejected">Reject</option></select><label class="form-label mt-3">Comment / rejection reason</label><textarea id="leaveDecisionReason" class="form-control" rows="3"></textarea></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button id="saveLeaveDecisionBtn" class="btn btn-primary">Save Decision</button></div></div></div></div>
<script src="<?= $appBase ?>/js/pages/staff_access.js"></script><script src="<?= $appBase ?>/js/pages/staff_leave.js"></script>
